-- PhxClaw v0.42 Project Management Suite
BEGIN;

CREATE TABLE IF NOT EXISTS pm_projects (
  tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, name text NOT NULL, methodology text NOT NULL DEFAULT 'hybrid', status text NOT NULL DEFAULT 'active', revision bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY (tenant_uuid, project_uuid)
);
CREATE TABLE IF NOT EXISTS pm_work_items (
  tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, work_item_uuid uuid NOT NULL, parent_uuid uuid NULL, title text NOT NULL, state text NOT NULL, priority integer NOT NULL DEFAULT 0, story_points numeric NULL, planned_start timestamptz NULL, planned_finish timestamptz NULL, actual_start timestamptz NULL, actual_finish timestamptz NULL, planned_cost numeric NOT NULL DEFAULT 0, actual_cost numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY (tenant_uuid, project_uuid, work_item_uuid), FOREIGN KEY (tenant_uuid, project_uuid) REFERENCES pm_projects(tenant_uuid, project_uuid)
);
CREATE TABLE IF NOT EXISTS pm_sprints (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, sprint_uuid uuid NOT NULL, name text NOT NULL, start_at timestamptz, end_at timestamptz, goal text, status text NOT NULL DEFAULT 'planned', PRIMARY KEY(tenant_uuid, project_uuid, sprint_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid));
CREATE TABLE IF NOT EXISTS pm_risks (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, risk_uuid uuid NOT NULL, title text NOT NULL, probability numeric NOT NULL, impact numeric NOT NULL, response text, status text NOT NULL DEFAULT 'open', PRIMARY KEY(tenant_uuid,project_uuid,risk_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid), CHECK(probability BETWEEN 0 AND 1), CHECK(impact BETWEEN 0 AND 1));
CREATE TABLE IF NOT EXISTS pm_cost_snapshots (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, snapshot_uuid uuid NOT NULL, pv numeric NOT NULL, ev numeric NOT NULL, ac numeric NOT NULL, bac numeric NOT NULL, captured_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,project_uuid,snapshot_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid));
CREATE TABLE IF NOT EXISTS pm_pdca_cycles (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, cycle_uuid uuid NOT NULL, phase text NOT NULL, objective text, metric jsonb NOT NULL DEFAULT '{}'::jsonb, evidence_sha256 text, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,project_uuid,cycle_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid));
CREATE TABLE IF NOT EXISTS pm_stakeholders (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, stakeholder_uuid uuid NOT NULL, display_name text NOT NULL, role text, influence integer, interest integer, communication_plan jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY(tenant_uuid,project_uuid,stakeholder_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid));
CREATE TABLE IF NOT EXISTS pm_events (tenant_uuid uuid NOT NULL, project_uuid uuid NOT NULL, event_uuid uuid NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL, evidence_sha256 text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,project_uuid,event_uuid), FOREIGN KEY(tenant_uuid,project_uuid) REFERENCES pm_projects(tenant_uuid,project_uuid));

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['pm_projects','pm_work_items','pm_sprints','pm_risks','pm_cost_snapshots','pm_pdca_cycles','pm_stakeholders','pm_events'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t); EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I',t); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_uuid = nullif(current_setting(''phxclaw.tenant_uuid'', true), )::uuid) WITH CHECK (tenant_uuid = nullif(current_setting(phxclaw.tenant_uuid, true), )::uuid)',t); END LOOP; END $$;

CREATE OR REPLACE FUNCTION pm_events_no_update_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'pm_events is append-only'; END $$;
DROP TRIGGER IF EXISTS pm_events_no_update ON pm_events; CREATE TRIGGER pm_events_no_update BEFORE UPDATE OR DELETE ON pm_events FOR EACH ROW EXECUTE FUNCTION pm_events_no_update_delete();
COMMIT;
