BEGIN;
CREATE TABLE IF NOT EXISTS phx_portfolio_execution_controllers(
 tenant_uuid uuid NOT NULL, controller_uuid uuid NOT NULL, portfolio_uuid uuid NOT NULL, active_plan_uuid uuid NOT NULL, active_plan_sha256 text NOT NULL CHECK(active_plan_sha256~'^[a-f0-9]{64}$'), source_state_sha256 text NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'), revision_no bigint NOT NULL CHECK(revision_no>=0), controller_epoch bigint NOT NULL CHECK(controller_epoch>0), fencing_token bigint NOT NULL CHECK(fencing_token>0), direct_mutation boolean NOT NULL DEFAULT false CHECK(direct_mutation=false), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,controller_uuid), UNIQUE(tenant_uuid,portfolio_uuid,controller_uuid));
CREATE TABLE IF NOT EXISTS phx_portfolio_execution_observations(
 tenant_uuid uuid NOT NULL, observation_uuid uuid NOT NULL, controller_uuid uuid NOT NULL, project_uuid uuid NOT NULL, observed_at timestamptz NOT NULL, source_state_sha256 text NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'), evidence_sha256 text NOT NULL CHECK(evidence_sha256~'^[a-f0-9]{64}$'), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,observation_uuid), FOREIGN KEY(tenant_uuid,controller_uuid) REFERENCES phx_portfolio_execution_controllers(tenant_uuid,controller_uuid));
CREATE TABLE IF NOT EXISTS phx_portfolio_drift_events(
 tenant_uuid uuid NOT NULL, drift_uuid uuid NOT NULL, controller_uuid uuid NOT NULL, project_uuid uuid NOT NULL, drift_kind text NOT NULL, severity text NOT NULL, magnitude numeric NOT NULL, confirmed boolean NOT NULL DEFAULT false, evidence_sha256 text NOT NULL CHECK(evidence_sha256~'^[a-f0-9]{64}$'), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,drift_uuid), FOREIGN KEY(tenant_uuid,controller_uuid) REFERENCES phx_portfolio_execution_controllers(tenant_uuid,controller_uuid));
CREATE TABLE IF NOT EXISTS phx_portfolio_replan_requests(
 tenant_uuid uuid NOT NULL, request_uuid uuid NOT NULL, controller_uuid uuid NOT NULL, base_plan_uuid uuid NOT NULL, base_plan_sha256 text NOT NULL CHECK(base_plan_sha256~'^[a-f0-9]{64}$'), base_revision_no bigint NOT NULL, source_state_sha256 text NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'), shadow_only boolean NOT NULL DEFAULT true CHECK(shadow_only=true), request_sha256 text NOT NULL CHECK(request_sha256~'^[a-f0-9]{64}$'), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,request_uuid), UNIQUE(tenant_uuid,request_uuid,request_sha256), FOREIGN KEY(tenant_uuid,controller_uuid) REFERENCES phx_portfolio_execution_controllers(tenant_uuid,controller_uuid));
CREATE TABLE IF NOT EXISTS phx_portfolio_plan_revision_proposals(
 tenant_uuid uuid NOT NULL, revision_uuid uuid NOT NULL, request_uuid uuid NOT NULL, base_plan_uuid uuid NOT NULL, base_plan_sha256 text NOT NULL CHECK(base_plan_sha256~'^[a-f0-9]{64}$'), candidate_plan_sha256 text NOT NULL CHECK(candidate_plan_sha256~'^[a-f0-9]{64}$'), source_state_sha256 text NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'), proposal_sha256 text NOT NULL CHECK(proposal_sha256~'^[a-f0-9]{64}$'), requires_approval boolean NOT NULL DEFAULT true CHECK(requires_approval=true), direct_mutation boolean NOT NULL DEFAULT false CHECK(direct_mutation=false), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,revision_uuid), UNIQUE(tenant_uuid,revision_uuid,proposal_sha256), FOREIGN KEY(tenant_uuid,request_uuid) REFERENCES phx_portfolio_replan_requests(tenant_uuid,request_uuid));
CREATE TABLE IF NOT EXISTS phx_portfolio_execution_events(
 tenant_uuid uuid NOT NULL, event_uuid uuid NOT NULL, controller_uuid uuid NOT NULL, event_type text NOT NULL, source_state_sha256 text NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'), evidence_sha256 text NOT NULL CHECK(evidence_sha256~'^[a-f0-9]{64}$'), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_uuid,event_uuid), FOREIGN KEY(tenant_uuid,controller_uuid) REFERENCES phx_portfolio_execution_controllers(tenant_uuid,controller_uuid));

DO $ddl$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['phx_portfolio_execution_controllers','phx_portfolio_execution_observations','phx_portfolio_drift_events','phx_portfolio_replan_requests','phx_portfolio_plan_revision_proposals','phx_portfolio_execution_events'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
  EXECUTE format($p$CREATE POLICY tenant_isolation ON %I USING (tenant_uuid = nullif(current_setting('phxclaw.tenant_uuid', true), '')::uuid) WITH CHECK (tenant_uuid = nullif(current_setting('phxclaw.tenant_uuid', true), '')::uuid)$p$,t);
 END LOOP;
END $ddl$;
CREATE OR REPLACE FUNCTION phx_portfolio_execution_append_only() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'append-only table';END$$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['phx_portfolio_execution_observations','phx_portfolio_drift_events','phx_portfolio_replan_requests','phx_portfolio_plan_revision_proposals','phx_portfolio_execution_events'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS zz_append_only ON %I',t); EXECUTE format('CREATE TRIGGER zz_append_only BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION phx_portfolio_execution_append_only()',t); END LOOP; END $$;
COMMIT;
