-- PhxClaw v0.63 — Native Repo Intelligence / Tree-sitter evidence store
CREATE SCHEMA IF NOT EXISTS phxclaw;
CREATE TABLE IF NOT EXISTS phxclaw.repo_analysis_runs(
 run_uuid uuid PRIMARY KEY,tenant_uuid uuid NOT NULL,repository_key text NOT NULL,repository_state_sha256 bytea NOT NULL CHECK(octet_length(repository_state_sha256)=32),
 analyzer_version text NOT NULL,tree_sitter_version text NOT NULL,status text NOT NULL CHECK(status IN('completed','partial','failed')),started_at timestamptz NOT NULL,completed_at timestamptz NOT NULL,
 CHECK(completed_at>=started_at),UNIQUE(tenant_uuid,repository_key,repository_state_sha256,analyzer_version));
CREATE TABLE IF NOT EXISTS phxclaw.repo_analysis_files(
 run_uuid uuid NOT NULL REFERENCES phxclaw.repo_analysis_runs(run_uuid) ON DELETE RESTRICT,file_path text NOT NULL,language text NOT NULL,content_sha256 bytea NOT NULL CHECK(octet_length(content_sha256)=32),
 byte_len bigint NOT NULL CHECK(byte_len>=0),line_count bigint NOT NULL CHECK(line_count>=0),parse_status text NOT NULL CHECK(parse_status IN('parsed','parsed_with_errors','unsupported_language','oversize','read_error','parser_error')),parse_error_nodes integer NOT NULL DEFAULT 0 CHECK(parse_error_nodes>=0),named_nodes bigint NOT NULL DEFAULT 0 CHECK(named_nodes>=0),PRIMARY KEY(run_uuid,file_path));
CREATE TABLE IF NOT EXISTS phxclaw.repo_symbols(
 run_uuid uuid NOT NULL REFERENCES phxclaw.repo_analysis_runs(run_uuid) ON DELETE RESTRICT,symbol_id char(64) NOT NULL CHECK(symbol_id~'^[a-f0-9]{64}$'),file_path text NOT NULL,language text NOT NULL,symbol_kind text NOT NULL,symbol_name text NOT NULL,qualified_hint text NOT NULL,
 start_row bigint NOT NULL,start_column bigint NOT NULL,end_row bigint NOT NULL,end_column bigint NOT NULL,complexity integer NOT NULL CHECK(complexity>=1),PRIMARY KEY(run_uuid,symbol_id),FOREIGN KEY(run_uuid,file_path) REFERENCES phxclaw.repo_analysis_files(run_uuid,file_path) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS phxclaw.repo_calls(
 run_uuid uuid NOT NULL REFERENCES phxclaw.repo_analysis_runs(run_uuid) ON DELETE RESTRICT,call_id char(64) NOT NULL CHECK(call_id~'^[a-f0-9]{64}$'),file_path text NOT NULL,caller_symbol_id char(64) NULL,target_text text NOT NULL,target_name text NOT NULL,resolved_symbol_ids jsonb NOT NULL DEFAULT '[]'::jsonb,start_row bigint NOT NULL,start_column bigint NOT NULL,end_row bigint NOT NULL,end_column bigint NOT NULL,PRIMARY KEY(run_uuid,call_id),FOREIGN KEY(run_uuid,file_path) REFERENCES phxclaw.repo_analysis_files(run_uuid,file_path) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS phxclaw.repo_dependencies(
 run_uuid uuid NOT NULL REFERENCES phxclaw.repo_analysis_runs(run_uuid) ON DELETE RESTRICT,dependency_id char(64) NOT NULL CHECK(dependency_id~'^[a-f0-9]{64}$'),file_path text NOT NULL,dependency_kind text NOT NULL,raw_text text NOT NULL,resolved_file text NULL,start_row bigint NOT NULL,start_column bigint NOT NULL,end_row bigint NOT NULL,end_column bigint NOT NULL,PRIMARY KEY(run_uuid,dependency_id),FOREIGN KEY(run_uuid,file_path) REFERENCES phxclaw.repo_analysis_files(run_uuid,file_path) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS phxclaw.repo_hotspots(
 run_uuid uuid NOT NULL REFERENCES phxclaw.repo_analysis_runs(run_uuid) ON DELETE RESTRICT,file_path text NOT NULL,pagerank_ppm integer NOT NULL CHECK(pagerank_ppm BETWEEN 0 AND 1000000),inbound_edges bigint NOT NULL CHECK(inbound_edges>=0),outbound_edges bigint NOT NULL CHECK(outbound_edges>=0),symbol_count bigint NOT NULL CHECK(symbol_count>=0),complexity bigint NOT NULL CHECK(complexity>=0),hotspot_score bigint NOT NULL CHECK(hotspot_score>=0),PRIMARY KEY(run_uuid,file_path),FOREIGN KEY(run_uuid,file_path) REFERENCES phxclaw.repo_analysis_files(run_uuid,file_path) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS repo_symbols_name_idx ON phxclaw.repo_symbols(run_uuid,symbol_name);
CREATE INDEX IF NOT EXISTS repo_calls_target_idx ON phxclaw.repo_calls(run_uuid,target_name);
CREATE INDEX IF NOT EXISTS repo_hotspots_score_idx ON phxclaw.repo_hotspots(run_uuid,hotspot_score DESC);
CREATE OR REPLACE FUNCTION phxclaw.reject_repo_intelligence_mutation() RETURNS trigger LANGUAGE plpgsql AS $fn$ BEGIN RAISE EXCEPTION 'repo intelligence evidence is append-only; create a new analysis run'; END $fn$;
DO $immut$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['repo_analysis_runs','repo_analysis_files','repo_symbols','repo_calls','repo_dependencies','repo_hotspots'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS %I ON phxclaw.%I','trg_'||t||'_immutable',t);EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON phxclaw.%I FOR EACH ROW EXECUTE FUNCTION phxclaw.reject_repo_intelligence_mutation()','trg_'||t||'_immutable',t);END LOOP;END $immut$;
DO $rls$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['repo_analysis_runs','repo_analysis_files','repo_symbols','repo_calls','repo_dependencies','repo_hotspots'] LOOP EXECUTE format('ALTER TABLE phxclaw.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE phxclaw.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_v063 ON phxclaw.%I',t);IF t='repo_analysis_runs' THEN EXECUTE 'CREATE POLICY tenant_isolation_v063 ON phxclaw.repo_analysis_runs USING (tenant_uuid=phxclaw.current_tenant_uuid()) WITH CHECK (tenant_uuid=phxclaw.current_tenant_uuid())';ELSE EXECUTE format('CREATE POLICY tenant_isolation_v063 ON phxclaw.%I USING (EXISTS (SELECT 1 FROM phxclaw.repo_analysis_runs r WHERE r.run_uuid=%I.run_uuid AND r.tenant_uuid=phxclaw.current_tenant_uuid())) WITH CHECK (EXISTS (SELECT 1 FROM phxclaw.repo_analysis_runs r WHERE r.run_uuid=%I.run_uuid AND r.tenant_uuid=phxclaw.current_tenant_uuid()))',t,t,t);END IF;END LOOP;END $rls$;
