BEGIN;
CREATE SCHEMA IF NOT EXISTS phxclaw;
CREATE TABLE IF NOT EXISTS phxclaw.research_records(
 research_uuid uuid PRIMARY KEY,tenant_uuid uuid NOT NULL,project_uuid uuid NULL,correlation_uuid uuid NOT NULL,topic text NOT NULL,question text NOT NULL,findings jsonb NOT NULL DEFAULT '[]'::jsonb,suggested_hypotheses jsonb NOT NULL DEFAULT '[]'::jsonb,source_state_sha256 char(64) NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'),created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS phxclaw.research_record_evidence(
 research_uuid uuid NOT NULL REFERENCES phxclaw.research_records(research_uuid) ON DELETE RESTRICT,evidence_uuid uuid NOT NULL,uri text NOT NULL,source_type text NOT NULL,retrieved_at timestamptz NOT NULL,sha256 char(64) NOT NULL CHECK(sha256~'^[a-f0-9]{64}$'),notes text NULL,PRIMARY KEY(research_uuid,evidence_uuid));
CREATE TABLE IF NOT EXISTS phxclaw.research_graph_links(
 research_uuid uuid NOT NULL REFERENCES phxclaw.research_records(research_uuid) ON DELETE RESTRICT,knowledge_node_uuid uuid NOT NULL REFERENCES phxclaw.knowledge_nodes(node_uuid) ON DELETE RESTRICT,role text NOT NULL CHECK(role IN('raw_source','claim','evidence','decision','related')),PRIMARY KEY(research_uuid,knowledge_node_uuid,role));

CREATE TABLE IF NOT EXISTS phxclaw.hypothesis_records(
 hypothesis_uuid uuid PRIMARY KEY,tenant_uuid uuid NOT NULL,research_uuid uuid NULL REFERENCES phxclaw.research_records(research_uuid) ON DELETE RESTRICT,statement text NOT NULL,rationale text NOT NULL,experiment_uuid uuid NOT NULL UNIQUE,current_status text NOT NULL CHECK(current_status IN('proposed','testing','supported','rejected','inconclusive')),source_state_sha256 char(64) NOT NULL CHECK(source_state_sha256~'^[a-f0-9]{64}$'),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS phxclaw.experiment_plans(
 experiment_uuid uuid PRIMARY KEY,hypothesis_uuid uuid NOT NULL UNIQUE REFERENCES phxclaw.hypothesis_records(hypothesis_uuid) ON DELETE RESTRICT,steps jsonb NOT NULL DEFAULT '[]'::jsonb,success_criteria jsonb NOT NULL DEFAULT '[]'::jsonb,failure_criteria jsonb NOT NULL DEFAULT '[]'::jsonb);
CREATE TABLE IF NOT EXISTS phxclaw.hypothesis_evidence(
 hypothesis_uuid uuid NOT NULL REFERENCES phxclaw.hypothesis_records(hypothesis_uuid) ON DELETE RESTRICT,evidence_uuid uuid NOT NULL,uri text NOT NULL,source_type text NOT NULL,retrieved_at timestamptz NOT NULL,sha256 char(64) NOT NULL CHECK(sha256~'^[a-f0-9]{64}$'),notes text NULL,PRIMARY KEY(hypothesis_uuid,evidence_uuid));
CREATE TABLE IF NOT EXISTS phxclaw.hypothesis_decisions(
 decision_uuid uuid PRIMARY KEY,hypothesis_uuid uuid NOT NULL REFERENCES phxclaw.hypothesis_records(hypothesis_uuid) ON DELETE RESTRICT,from_status text NULL CHECK(from_status IS NULL OR from_status IN('proposed','testing','supported','rejected','inconclusive')),to_status text NOT NULL CHECK(to_status IN('proposed','testing','supported','rejected','inconclusive')),note text NOT NULL,actor text NOT NULL,decided_at timestamptz NOT NULL DEFAULT clock_timestamp(),import_order integer NULL,UNIQUE(hypothesis_uuid,import_order));
CREATE TABLE IF NOT EXISTS phxclaw.experiment_runs(
 run_uuid uuid PRIMARY KEY,tenant_uuid uuid NOT NULL,hypothesis_uuid uuid NOT NULL REFERENCES phxclaw.hypothesis_records(hypothesis_uuid) ON DELETE RESTRICT,state text NOT NULL CHECK(state IN('running','completed','failed','cancelled')),success boolean NULL,result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,started_at timestamptz NOT NULL,completed_at timestamptz NULL,CHECK((state='running' AND completed_at IS NULL) OR state<>'running'));
CREATE TABLE IF NOT EXISTS phxclaw.experiment_run_evidence(
 run_uuid uuid NOT NULL REFERENCES phxclaw.experiment_runs(run_uuid) ON DELETE RESTRICT,evidence_uuid uuid NOT NULL,uri text NOT NULL,source_type text NOT NULL,retrieved_at timestamptz NOT NULL,sha256 char(64) NOT NULL CHECK(sha256~'^[a-f0-9]{64}$'),notes text NULL,PRIMARY KEY(run_uuid,evidence_uuid));
CREATE TABLE IF NOT EXISTS phxclaw.hypothesis_graph_links(
 hypothesis_uuid uuid NOT NULL REFERENCES phxclaw.hypothesis_records(hypothesis_uuid) ON DELETE RESTRICT,knowledge_node_uuid uuid NOT NULL REFERENCES phxclaw.knowledge_nodes(node_uuid) ON DELETE RESTRICT,role text NOT NULL CHECK(role IN('hypothesis','claim','evidence','decision','experiment')),PRIMARY KEY(hypothesis_uuid,knowledge_node_uuid,role));

CREATE INDEX IF NOT EXISTS research_records_tenant_created_idx ON phxclaw.research_records(tenant_uuid,created_at DESC);
CREATE INDEX IF NOT EXISTS hypothesis_records_tenant_status_idx ON phxclaw.hypothesis_records(tenant_uuid,current_status,updated_at DESC);
CREATE INDEX IF NOT EXISTS experiment_runs_tenant_started_idx ON phxclaw.experiment_runs(tenant_uuid,started_at DESC);

CREATE OR REPLACE FUNCTION phxclaw.reject_research_hypothesis_delete() RETURNS trigger LANGUAGE plpgsql AS $fn$ BEGIN RAISE EXCEPTION 'research/hypothesis evidence cannot be deleted'; END $fn$;
DO $no_delete$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['research_records','research_record_evidence','research_graph_links','hypothesis_records','experiment_plans','hypothesis_evidence','hypothesis_decisions','experiment_runs','experiment_run_evidence','hypothesis_graph_links'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS %I ON phxclaw.%I','trg_'||t||'_no_delete',t);EXECUTE format('CREATE TRIGGER %I BEFORE DELETE ON phxclaw.%I FOR EACH ROW EXECUTE FUNCTION phxclaw.reject_research_hypothesis_delete()','trg_'||t||'_no_delete',t);END LOOP;END $no_delete$;

DO $rls$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['research_records','hypothesis_records','experiment_runs'] LOOP EXECUTE format('ALTER TABLE phxclaw.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE phxclaw.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_v066 ON phxclaw.%I',t);EXECUTE format('CREATE POLICY tenant_isolation_v066 ON phxclaw.%I USING (tenant_uuid=phxclaw.current_tenant_uuid()) WITH CHECK (tenant_uuid=phxclaw.current_tenant_uuid())',t);END LOOP;
 FOREACH t IN ARRAY ARRAY['research_record_evidence','research_graph_links'] LOOP EXECUTE format('ALTER TABLE phxclaw.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE phxclaw.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_v066 ON phxclaw.%I',t);EXECUTE format('CREATE POLICY tenant_isolation_v066 ON phxclaw.%I USING (EXISTS(SELECT 1 FROM phxclaw.research_records r WHERE r.research_uuid=%I.research_uuid AND r.tenant_uuid=phxclaw.current_tenant_uuid())) WITH CHECK (EXISTS(SELECT 1 FROM phxclaw.research_records r WHERE r.research_uuid=%I.research_uuid AND r.tenant_uuid=phxclaw.current_tenant_uuid()))',t,t,t);END LOOP;
 FOREACH t IN ARRAY ARRAY['experiment_plans','hypothesis_evidence','hypothesis_decisions','hypothesis_graph_links'] LOOP EXECUTE format('ALTER TABLE phxclaw.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE phxclaw.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_v066 ON phxclaw.%I',t);EXECUTE format('CREATE POLICY tenant_isolation_v066 ON phxclaw.%I USING (EXISTS(SELECT 1 FROM phxclaw.hypothesis_records h WHERE h.hypothesis_uuid=%I.hypothesis_uuid AND h.tenant_uuid=phxclaw.current_tenant_uuid())) WITH CHECK (EXISTS(SELECT 1 FROM phxclaw.hypothesis_records h WHERE h.hypothesis_uuid=%I.hypothesis_uuid AND h.tenant_uuid=phxclaw.current_tenant_uuid()))',t,t,t);END LOOP;
 ALTER TABLE phxclaw.experiment_run_evidence ENABLE ROW LEVEL SECURITY;ALTER TABLE phxclaw.experiment_run_evidence FORCE ROW LEVEL SECURITY;DROP POLICY IF EXISTS tenant_isolation_v066 ON phxclaw.experiment_run_evidence;CREATE POLICY tenant_isolation_v066 ON phxclaw.experiment_run_evidence USING(EXISTS(SELECT 1 FROM phxclaw.experiment_runs x WHERE x.run_uuid=experiment_run_evidence.run_uuid AND x.tenant_uuid=phxclaw.current_tenant_uuid())) WITH CHECK(EXISTS(SELECT 1 FROM phxclaw.experiment_runs x WHERE x.run_uuid=experiment_run_evidence.run_uuid AND x.tenant_uuid=phxclaw.current_tenant_uuid()));
END $rls$;
COMMIT;
