use async_trait::async_trait;
use phx_sql_introspection_api::*;
use phx_sql_model::{ObjectKind, Partitioning, TableStatistics};
use phx_sql_parser_api::SqlDialect;
use sqlx::{mysql::MySqlPoolOptions, Row};
use std::collections::{BTreeMap,BTreeSet,HashMap};
use std::time::Duration;

pub struct MySqlIntrospector;
fn empty_table(schema:String,name:String)->CatalogTable{CatalogTable{schema,name,columns:vec![],primary_key:vec![],foreign_keys:vec![],check_constraints:vec![],partitioning:None,statistics:None,definition:None}}
fn obj(kind:ObjectKind,schema:Option<String>,name:String,target:Option<String>,definition:Option<String>)->CatalogObject{CatalogObject{kind,schema,name,target,definition,metadata:BTreeMap::new()}}
#[async_trait]
impl DatabaseIntrospector for MySqlIntrospector{
 fn dialect(&self)->SqlDialect{SqlDialect::MySql}
 async fn introspect(&self,spec:&ConnectionSpec,options:&IntrospectionOptions)->Result<CatalogSnapshot,IntrospectionError>{
  if spec.dialect!=SqlDialect::MySql{return Err(IntrospectionError::UnsupportedDialect(spec.dialect.as_str().into()))}
  let user=spec.username.clone().unwrap_or_default();let pass=spec.password.clone().unwrap_or_default();let url=format!("mysql://{}:{}@{}:{}/{}",urlencoding(&user),urlencoding(&pass),spec.host,spec.port.unwrap_or(3306),spec.database);
  let pool=MySqlPoolOptions::new().max_connections(2).acquire_timeout(Duration::from_secs(12)).connect(&url).await.map_err(|e|IntrospectionError::Connection(e.to_string()))?;
  let rows=sqlx::query(r#"SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,ORDINAL_POSITION,GENERATION_EXPRESSION,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME,ORDINAL_POSITION"#).bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut tables:HashMap<(String,String),CatalogTable>=HashMap::new();for r in rows{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();let e=tables.entry((s.to_ascii_lowercase(),t.to_ascii_lowercase())).or_insert_with(||empty_table(s.clone(),t.clone()));let expr=r.try_get::<String,_>("GENERATION_EXPRESSION").ok().filter(|x|!x.is_empty());let extra=r.try_get::<String,_>("EXTRA").unwrap_or_default().to_ascii_lowercase();e.columns.push(CatalogColumn{name:r.try_get("COLUMN_NAME").unwrap_or_default(),data_type:r.try_get("COLUMN_TYPE").unwrap_or_default(),nullable:r.try_get::<String,_>("IS_NULLABLE").unwrap_or_default()=="YES",default_expr:r.try_get("COLUMN_DEFAULT").ok(),primary_key:false,unique:false,ordinal:r.try_get::<i64,_>("ORDINAL_POSITION").unwrap_or(0).max(0)as usize,generated_expression:expr,generated_kind:if extra.contains("stored generated"){Some("stored".into())}else if extra.contains("virtual generated"){Some("virtual".into())}else{None}});}
  if tables.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(tables.len()))}
  let kr=sqlx::query(r#"SELECT tc.TABLE_SCHEMA,tc.TABLE_NAME,tc.CONSTRAINT_NAME,tc.CONSTRAINT_TYPE,kcu.COLUMN_NAME,kcu.ORDINAL_POSITION FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.KEY_COLUMN_USAGE kcu ON kcu.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND kcu.TABLE_NAME=tc.TABLE_NAME AND kcu.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.TABLE_SCHEMA=? AND tc.CONSTRAINT_TYPE IN ('PRIMARY KEY','UNIQUE') ORDER BY tc.TABLE_NAME,tc.CONSTRAINT_NAME,kcu.ORDINAL_POSITION"#).bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut pk:HashMap<(String,String),Vec<(usize,String)>>=HashMap::new();let mut ug:HashMap<(String,String,String),Vec<String>>=HashMap::new();for r in kr{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();let ty:String=r.try_get("CONSTRAINT_TYPE").unwrap_or_default();let c:String=r.try_get("COLUMN_NAME").unwrap_or_default();if ty=="PRIMARY KEY"{pk.entry((s.to_ascii_lowercase(),t.to_ascii_lowercase())).or_default().push((r.try_get::<i64,_>("ORDINAL_POSITION").unwrap_or(0).max(0)as usize,c));}else{ug.entry((s.to_ascii_lowercase(),t.to_ascii_lowercase(),r.try_get("CONSTRAINT_NAME").unwrap_or_default())).or_default().push(c);}}
  let primary:HashMap<_,_>=pk.into_iter().map(|(k,mut v)|{v.sort_by_key(|x|x.0);(k,v.into_iter().map(|x|x.1).collect())}).collect();let mut uniques:HashMap<(String,String),BTreeSet<String>>=HashMap::new();for((s,t,_),v)in ug{if v.len()==1{uniques.entry((s,t)).or_default().insert(v[0].to_ascii_lowercase());}}
  let fkrows=sqlx::query(r#"SELECT kcu.CONSTRAINT_NAME,kcu.TABLE_SCHEMA,kcu.TABLE_NAME,kcu.COLUMN_NAME,kcu.ORDINAL_POSITION,kcu.REFERENCED_TABLE_SCHEMA,kcu.REFERENCED_TABLE_NAME,kcu.REFERENCED_COLUMN_NAME,rc.DELETE_RULE FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON rc.CONSTRAINT_SCHEMA=kcu.CONSTRAINT_SCHEMA AND rc.CONSTRAINT_NAME=kcu.CONSTRAINT_NAME WHERE kcu.TABLE_SCHEMA=? AND kcu.REFERENCED_TABLE_NAME IS NOT NULL ORDER BY kcu.TABLE_NAME,kcu.CONSTRAINT_NAME,kcu.ORDINAL_POSITION"#).bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  #[derive(Default)]struct F{fs:String,ft:String,ts:String,tt:String,a:Vec<(usize,String)>,b:Vec<(usize,String)>,name:String,del:Option<String>}let mut fgs:HashMap<String,F>=HashMap::new();for r in fkrows{let fs:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let ft:String=r.try_get("TABLE_NAME").unwrap_or_default();let n:String=r.try_get("CONSTRAINT_NAME").unwrap_or_default();let g=fgs.entry(format!("{fs}.{ft}:{n}")).or_default();g.fs=fs;g.ft=ft;g.ts=r.try_get("REFERENCED_TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());g.tt=r.try_get("REFERENCED_TABLE_NAME").unwrap_or_default();g.name=n;let o=r.try_get::<i64,_>("ORDINAL_POSITION").unwrap_or(0).max(0)as usize;g.a.push((o,r.try_get("COLUMN_NAME").unwrap_or_default()));g.b.push((o,r.try_get("REFERENCED_COLUMN_NAME").unwrap_or_default()));g.del=r.try_get("DELETE_RULE").ok();}for(_,mut g)in fgs{g.a.sort_by_key(|x|x.0);g.b.sort_by_key(|x|x.0);if let Some(t)=tables.get_mut(&(g.fs.to_ascii_lowercase(),g.ft.to_ascii_lowercase())){t.foreign_keys.push(CatalogForeignKey{constraint_name:Some(g.name),from_schema:g.fs,from_table:g.ft,from_columns:g.a.into_iter().map(|x|x.1).collect(),to_schema:g.ts,to_table:g.tt,to_columns:g.b.into_iter().map(|x|x.1).collect(),on_delete:g.del});}}
  let checks=sqlx::query(r#"SELECT tc.TABLE_SCHEMA,tc.TABLE_NAME,tc.CONSTRAINT_NAME,cc.CHECK_CLAUSE FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.TABLE_SCHEMA=? AND tc.CONSTRAINT_TYPE='CHECK' ORDER BY tc.TABLE_NAME,tc.CONSTRAINT_NAME"#).bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;for r in checks{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();if let Some(tab)=tables.get_mut(&(s.to_ascii_lowercase(),t.to_ascii_lowercase())){tab.check_constraints.push(CatalogCheckConstraint{name:r.try_get("CONSTRAINT_NAME").ok(),expression:r.try_get("CHECK_CLAUSE").unwrap_or_default(),column:None});}}
  if options.include_statistics{let sr=sqlx::query("SELECT TABLE_SCHEMA,TABLE_NAME,TABLE_ROWS,DATA_LENGTH,INDEX_LENGTH FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_TYPE='BASE TABLE'").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;for r in sr{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();if let Some(tab)=tables.get_mut(&(s.to_ascii_lowercase(),t.to_ascii_lowercase())){let rows=r.try_get::<i64,_>("TABLE_ROWS").ok().filter(|v|*v>=0).map(|v|v as u64);let d=r.try_get::<i64,_>("DATA_LENGTH").ok().filter(|v|*v>=0).map(|v|v as u64);let i=r.try_get::<i64,_>("INDEX_LENGTH").ok().filter(|v|*v>=0).map(|v|v as u64);tab.statistics=Some(TableStatistics{estimated_rows:rows,data_bytes:d,index_bytes:i,total_bytes:Some(d.unwrap_or(0)+i.unwrap_or(0))});}}}
  let mut objects=vec![obj(ObjectKind::Schema,None,spec.database.clone(),None,None)];
  if options.include_advanced_objects{let pr=sqlx::query("SELECT TABLE_SCHEMA,TABLE_NAME,PARTITION_NAME,PARTITION_METHOD,PARTITION_EXPRESSION,PARTITION_DESCRIPTION,TABLE_ROWS,DATA_LENGTH,INDEX_LENGTH FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA=? AND PARTITION_NAME IS NOT NULL ORDER BY TABLE_NAME,PARTITION_ORDINAL_POSITION").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;for r in pr{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();let method:String=r.try_get("PARTITION_METHOD").unwrap_or_default();let expr:String=r.try_get("PARTITION_EXPRESSION").unwrap_or_default();if let Some(tab)=tables.get_mut(&(s.to_ascii_lowercase(),t.to_ascii_lowercase())){tab.partitioning=Some(Partitioning{kind:method.to_ascii_lowercase(),expression:Some(expr.clone()),parent:None,bound:None});}let mut o=obj(ObjectKind::Partition,Some(s.clone()),r.try_get("PARTITION_NAME").unwrap_or_default(),Some(format!("{s}.{t}")),None);o.metadata.insert("method".into(),method);o.metadata.insert("expression".into(),expr);o.metadata.insert("description".into(),r.try_get::<String,_>("PARTITION_DESCRIPTION").unwrap_or_default());objects.push(o);}
   for r in sqlx::query("SELECT EVENT_SCHEMA,EVENT_NAME,EVENT_DEFINITION,EVENT_TYPE,EXECUTE_AT,INTERVAL_VALUE,INTERVAL_FIELD,STATUS FROM information_schema.EVENTS WHERE EVENT_SCHEMA=? ORDER BY EVENT_NAME").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let mut o=obj(ObjectKind::Event,Some(r.try_get("EVENT_SCHEMA").unwrap_or_else(|_|spec.database.clone())),r.try_get("EVENT_NAME").unwrap_or_default(),None,r.try_get("EVENT_DEFINITION").ok());o.metadata.insert("event_type".into(),r.try_get::<String,_>("EVENT_TYPE").unwrap_or_default());o.metadata.insert("status".into(),r.try_get::<String,_>("STATUS").unwrap_or_default());objects.push(o);}}
  if options.include_views{for r in sqlx::query("SELECT TABLE_SCHEMA,TABLE_NAME,VIEW_DEFINITION FROM information_schema.VIEWS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{objects.push(obj(ObjectKind::View,Some(r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone())),r.try_get("TABLE_NAME").unwrap_or_default(),None,r.try_get("VIEW_DEFINITION").ok()));}}
  if options.include_indexes{for r in sqlx::query("SELECT TABLE_SCHEMA,TABLE_NAME,INDEX_NAME,GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) COLS FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? GROUP BY TABLE_SCHEMA,TABLE_NAME,INDEX_NAME ORDER BY TABLE_NAME,INDEX_NAME").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("TABLE_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("TABLE_NAME").unwrap_or_default();objects.push(obj(ObjectKind::Index,Some(s.clone()),r.try_get("INDEX_NAME").unwrap_or_default(),Some(format!("{s}.{t}")),Some(format!("INDEX ({})",r.try_get::<String,_>("COLS").unwrap_or_default()))));}}
  if options.include_routines{for r in sqlx::query("SELECT ROUTINE_SCHEMA,ROUTINE_NAME,ROUTINE_DEFINITION FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA=? ORDER BY ROUTINE_NAME").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{objects.push(obj(ObjectKind::Function,Some(r.try_get("ROUTINE_SCHEMA").unwrap_or_else(|_|spec.database.clone())),r.try_get("ROUTINE_NAME").unwrap_or_default(),None,r.try_get("ROUTINE_DEFINITION").ok()));}}
  if options.include_triggers{for r in sqlx::query("SELECT TRIGGER_SCHEMA,TRIGGER_NAME,EVENT_OBJECT_SCHEMA,EVENT_OBJECT_TABLE,ACTION_STATEMENT FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=? ORDER BY TRIGGER_NAME").bind(&spec.database).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("TRIGGER_SCHEMA").unwrap_or_else(|_|spec.database.clone());let ts:String=r.try_get("EVENT_OBJECT_SCHEMA").unwrap_or_else(|_|spec.database.clone());let t:String=r.try_get("EVENT_OBJECT_TABLE").unwrap_or_default();objects.push(obj(ObjectKind::Trigger,Some(s),r.try_get("TRIGGER_NAME").unwrap_or_default(),Some(format!("{ts}.{t}")),r.try_get("ACTION_STATEMENT").ok()));}}
  let mut tv=tables.into_values().collect::<Vec<_>>();tv.sort_by(|a,b|a.name.cmp(&b.name));apply_key_flags(&mut tv,&primary,&uniques);if tv.len()+objects.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(tv.len()+objects.len()))}
  Ok(CatalogSnapshot{dialect:SqlDialect::MySql,source_name:spec.safe_source_name(),database_name:spec.database.clone(),tables:tv,objects})
 }
}
fn urlencoding(s:&str)->String{s.bytes().map(|b|if b.is_ascii_alphanumeric()||b"-._~".contains(&b){(b as char).to_string()}else{format!("%{b:02X}")}).collect()}
