use async_trait::async_trait;
use phx_sql_introspection_api::*;
use phx_sql_model::{ObjectKind,Partitioning,TableStatistics};
use phx_sql_parser_api::SqlDialect;
use std::collections::{BTreeMap,BTreeSet,HashMap};
use tiberius::{AuthMethod,Client,Config,EncryptionLevel,Row};
use tokio::net::TcpStream;
use tokio_util::compat::{Compat,TokioAsyncWriteCompatExt};

pub struct SqlServerIntrospector;type MsClient=Client<Compat<TcpStream>>;
fn s(r:&Row,n:&str)->String{r.get::<&str,_>(n).unwrap_or("").to_owned()}fn os(r:&Row,n:&str)->Option<String>{r.get::<&str,_>(n).map(str::to_owned)}fn i(r:&Row,n:&str)->i32{r.get::<i32,_>(n).unwrap_or(0)}
fn allowed_schema(s:&str,o:&IntrospectionOptions)->bool{if !o.schemas.is_empty()&&!o.schemas.iter().any(|x|x.eq_ignore_ascii_case(s)){return false}o.include_system||!matches!(s,"sys"|"INFORMATION_SCHEMA")}
fn empty_table(schema:String,name:String)->CatalogTable{CatalogTable{schema,name,columns:vec![],primary_key:vec![],foreign_keys:vec![],check_constraints:vec![],partitioning:None,statistics:None,definition:None}}
fn obj(kind:ObjectKind,schema:Option<String>,name:String,target:Option<String>,definition:Option<String>)->CatalogObject{CatalogObject{kind,schema,name,target,definition,metadata:BTreeMap::new()}}
async fn connect(spec:&ConnectionSpec)->Result<MsClient,IntrospectionError>{let mut c=Config::new();c.host(&spec.host);c.port(spec.port.unwrap_or(1433));c.database(&spec.database);c.readonly(true);let u=spec.username.as_deref().ok_or_else(||IntrospectionError::InvalidInput("SQL Server requer username".into()))?;c.authentication(AuthMethod::sql_server(u,spec.password.as_deref().unwrap_or("")));match spec.tls{TlsMode::Disable=>c.encryption(EncryptionLevel::NotSupported),_=>c.encryption(EncryptionLevel::Required)}let tcp=TcpStream::connect(c.get_addr()).await.map_err(|e|IntrospectionError::Connection(e.to_string()))?;tcp.set_nodelay(true).map_err(|e|IntrospectionError::Connection(e.to_string()))?;Client::connect(c,tcp.compat_write()).await.map_err(|e|IntrospectionError::Connection(e.to_string()))}
async fn rows(c:&mut MsClient,q:&str)->Result<Vec<Row>,IntrospectionError>{c.simple_query(q).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?.into_first_result().await.map_err(|e|IntrospectionError::Catalog(e.to_string()))}

#[async_trait]
impl DatabaseIntrospector for SqlServerIntrospector{
 fn dialect(&self)->SqlDialect{SqlDialect::SqlServer}
 async fn introspect(&self,spec:&ConnectionSpec,opt:&IntrospectionOptions)->Result<CatalogSnapshot,IntrospectionError>{
  if spec.dialect!=SqlDialect::SqlServer{return Err(IntrospectionError::UnsupportedDialect(spec.dialect.as_str().into()))}let mut client=connect(spec).await?;
  let cr=rows(&mut client,r#"SELECT s.name schema_name,t.name table_name,c.name column_name,ty.name data_type,c.is_nullable,dc.definition default_expr,c.column_id ordinal_position,c.is_computed,cc.definition computed_definition,cc.is_persisted FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.columns c ON c.object_id=t.object_id JOIN sys.types ty ON ty.user_type_id=c.user_type_id LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id LEFT JOIN sys.computed_columns cc ON cc.object_id=c.object_id AND cc.column_id=c.column_id WHERE t.is_ms_shipped=0 ORDER BY s.name,t.name,c.column_id"#).await?;let mut tables:HashMap<(String,String),CatalogTable>=HashMap::new();for r in cr{let sc=s(&r,"schema_name");if !allowed_schema(&sc,opt){continue}let tn=s(&r,"table_name");let e=tables.entry((sc.to_ascii_lowercase(),tn.to_ascii_lowercase())).or_insert_with(||empty_table(sc.clone(),tn.clone()));let comp=r.get::<bool,_>("is_computed").unwrap_or(false);e.columns.push(CatalogColumn{name:s(&r,"column_name"),data_type:s(&r,"data_type"),nullable:r.get::<bool,_>("is_nullable").unwrap_or(true),default_expr:os(&r,"default_expr"),primary_key:false,unique:false,ordinal:i(&r,"ordinal_position").max(0)as usize,generated_expression:if comp{os(&r,"computed_definition")}else{None},generated_kind:if comp{Some(if r.get::<bool,_>("is_persisted").unwrap_or(false){"persisted"}else{"virtual"}.into())}else{None}});}if tables.len()>opt.max_objects{return Err(IntrospectionError::ObjectLimit(tables.len()))}
  let keys=rows(&mut client,"SELECT s.name schema_name,t.name table_name,i.name constraint_name,i.is_primary_key,i.is_unique_constraint,c.name column_name,ic.key_ordinal FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE (i.is_primary_key=1 OR i.is_unique_constraint=1) AND ic.key_ordinal>0 ORDER BY s.name,t.name,i.name,ic.key_ordinal").await?;let mut kg:HashMap<(String,String,String,bool),Vec<(i32,String)>>=HashMap::new();for r in keys{let sc=s(&r,"schema_name");if !allowed_schema(&sc,opt){continue}kg.entry((sc.to_ascii_lowercase(),s(&r,"table_name").to_ascii_lowercase(),s(&r,"constraint_name"),r.get::<bool,_>("is_primary_key").unwrap_or(false))).or_default().push((i(&r,"key_ordinal"),s(&r,"column_name")));}let mut pks=HashMap::new();let mut uq:HashMap<(String,String),BTreeSet<String>>=HashMap::new();for((sc,tn,_,pk),mut cs)in kg{cs.sort_by_key(|x|x.0);let names=cs.into_iter().map(|x|x.1).collect::<Vec<_>>();if pk{pks.insert((sc,tn),names)}else if names.len()==1{uq.entry((sc,tn)).or_default().insert(names[0].to_ascii_lowercase());}}
  let fr=rows(&mut client,"SELECT fk.name constraint_name,sp.name from_schema,tp.name from_table,cp.name from_column,sr.name to_schema,tr.name to_table,cr.name to_column,fkc.constraint_column_id ordinal_position,fk.delete_referential_action_desc delete_rule FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id JOIN sys.tables tp ON tp.object_id=fk.parent_object_id JOIN sys.schemas sp ON sp.schema_id=tp.schema_id JOIN sys.columns cp ON cp.object_id=tp.object_id AND cp.column_id=fkc.parent_column_id JOIN sys.tables tr ON tr.object_id=fk.referenced_object_id JOIN sys.schemas sr ON sr.schema_id=tr.schema_id JOIN sys.columns cr ON cr.object_id=tr.object_id AND cr.column_id=fkc.referenced_column_id ORDER BY sp.name,tp.name,fk.name,fkc.constraint_column_id").await?;#[derive(Default)]struct G{fs:String,ft:String,ts:String,tt:String,a:Vec<(i32,String)>,b:Vec<(i32,String)>,n:String,d:Option<String>}let mut gs:HashMap<String,G>=HashMap::new();for r in fr{let fs=s(&r,"from_schema");if !allowed_schema(&fs,opt){continue}let ft=s(&r,"from_table");let n=s(&r,"constraint_name");let g=gs.entry(format!("{fs}.{ft}:{n}")).or_default();g.fs=fs;g.ft=ft;g.ts=s(&r,"to_schema");g.tt=s(&r,"to_table");g.n=n;let o=i(&r,"ordinal_position");g.a.push((o,s(&r,"from_column")));g.b.push((o,s(&r,"to_column")));g.d=os(&r,"delete_rule");}for(_,mut g)in gs{g.a.sort_by_key(|x|x.0);g.b.sort_by_key(|x|x.0);if let Some(t)=tables.get_mut(&(g.fs.to_ascii_lowercase(),g.ft.to_ascii_lowercase())){t.foreign_keys.push(CatalogForeignKey{constraint_name:Some(g.n),from_schema:g.fs,from_table:g.ft,from_columns:g.a.into_iter().map(|x|x.1).collect(),to_schema:g.ts,to_table:g.tt,to_columns:g.b.into_iter().map(|x|x.1).collect(),on_delete:g.d});}}
  for r in rows(&mut client,"SELECT s.name schema_name,t.name table_name,cc.name constraint_name,cc.definition FROM sys.check_constraints cc JOIN sys.tables t ON t.object_id=cc.parent_object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE t.is_ms_shipped=0 ORDER BY s.name,t.name,cc.name").await?{let sc=s(&r,"schema_name");if !allowed_schema(&sc,opt){continue}let tn=s(&r,"table_name");if let Some(t)=tables.get_mut(&(sc.to_ascii_lowercase(),tn.to_ascii_lowercase())){t.check_constraints.push(CatalogCheckConstraint{name:Some(s(&r,"constraint_name")),expression:s(&r,"definition"),column:None});}}
  if opt.include_statistics{for r in rows(&mut client,r#"SELECT s.name schema_name,t.name table_name,SUM(ps.row_count) estimated_rows,SUM(ps.used_page_count)*8192 used_bytes,SUM(ps.reserved_page_count)*8192 total_bytes,COUNT(DISTINCT ps.partition_number) partition_count FROM sys.dm_db_partition_stats ps JOIN sys.tables t ON t.object_id=ps.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE ps.index_id IN (0,1) AND t.is_ms_shipped=0 GROUP BY s.name,t.name"#).await?{let sc=s(&r,"schema_name");if !allowed_schema(&sc,opt){continue}let tn=s(&r,"table_name");if let Some(t)=tables.get_mut(&(sc.to_ascii_lowercase(),tn.to_ascii_lowercase())){let er=r.get::<i64,_>("estimated_rows").filter(|v|*v>=0).map(|v|v as u64);let used=r.get::<i64,_>("used_bytes").filter(|v|*v>=0).map(|v|v as u64);let total=r.get::<i64,_>("total_bytes").filter(|v|*v>=0).map(|v|v as u64);t.statistics=Some(TableStatistics{estimated_rows:er,data_bytes:used,index_bytes:None,total_bytes:total});if i(&r,"partition_count")>1{t.partitioning=Some(Partitioning{kind:"partition_scheme".into(),expression:None,parent:None,bound:None});}}}}
  let mut tv=tables.into_values().collect::<Vec<_>>();tv.sort_by(|a,b|(&a.schema,&a.name).cmp(&(&b.schema,&b.name)));apply_key_flags(&mut tv,&pks,&uq);let mut objects=vec![];
  if opt.include_views{for r in rows(&mut client,"SELECT s.name schema_name,v.name object_name,OBJECT_DEFINITION(v.object_id) definition FROM sys.views v JOIN sys.schemas s ON s.schema_id=v.schema_id WHERE v.is_ms_shipped=0 ORDER BY s.name,v.name").await?{let sc=s(&r,"schema_name");if allowed_schema(&sc,opt){objects.push(obj(ObjectKind::View,Some(sc),s(&r,"object_name"),None,os(&r,"definition")));}}}
  if opt.include_routines{for r in rows(&mut client,"SELECT s.name schema_name,o.name object_name,OBJECT_DEFINITION(o.object_id) definition FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE o.is_ms_shipped=0 AND o.type IN ('P','FN','IF','TF') ORDER BY s.name,o.name").await?{let sc=s(&r,"schema_name");if allowed_schema(&sc,opt){objects.push(obj(ObjectKind::Function,Some(sc),s(&r,"object_name"),None,os(&r,"definition")));}}}
  if opt.include_triggers{for r in rows(&mut client,"SELECT s.name schema_name,tr.name object_name,OBJECT_SCHEMA_NAME(tr.parent_id) target_schema,OBJECT_NAME(tr.parent_id) target_table,OBJECT_DEFINITION(tr.object_id) definition FROM sys.triggers tr LEFT JOIN sys.objects o ON o.object_id=tr.parent_id LEFT JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE tr.is_ms_shipped=0 ORDER BY s.name,tr.name").await?{let sc=s(&r,"schema_name");if sc.is_empty()||allowed_schema(&sc,opt){let ts=s(&r,"target_schema");let tt=s(&r,"target_table");objects.push(obj(ObjectKind::Trigger,if sc.is_empty(){None}else{Some(sc)},s(&r,"object_name"),if tt.is_empty(){None}else{Some(format!("{ts}.{tt}"))},os(&r,"definition")));}}}
  if opt.include_indexes{for r in rows(&mut client,"SELECT s.name schema_name,t.name table_name,i.name object_name FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE t.is_ms_shipped=0 AND i.index_id>0 AND i.name IS NOT NULL ORDER BY s.name,t.name,i.name").await?{let sc=s(&r,"schema_name");if allowed_schema(&sc,opt){let tt=s(&r,"table_name");objects.push(obj(ObjectKind::Index,Some(sc.clone()),s(&r,"object_name"),Some(format!("{sc}.{tt}")),None));}}}
  if opt.include_advanced_objects{for r in rows(&mut client,"SELECT s.name schema_name,sy.name object_name,sy.base_object_name FROM sys.synonyms sy JOIN sys.schemas s ON s.schema_id=sy.schema_id ORDER BY s.name,sy.name").await?{let sc=s(&r,"schema_name");if allowed_schema(&sc,opt){let mut o=obj(ObjectKind::Synonym,Some(sc),s(&r,"object_name"),os(&r,"base_object_name"),None);o.metadata.insert("base_object".into(),s(&r,"base_object_name"));objects.push(o);}}for r in rows(&mut client,"SELECT s.name schema_name,seq.name object_name,TYPE_NAME(seq.user_type_id) data_type,seq.start_value,seq.increment FROM sys.sequences seq JOIN sys.schemas s ON s.schema_id=seq.schema_id ORDER BY s.name,seq.name").await?{let sc=s(&r,"schema_name");if allowed_schema(&sc,opt){let mut o=obj(ObjectKind::Sequence,Some(sc),s(&r,"object_name"),None,None);o.metadata.insert("data_type".into(),s(&r,"data_type"));objects.push(o);}}}
  let schemas:BTreeSet<_>=tv.iter().map(|t|t.schema.clone()).collect();for sc in schemas{objects.push(obj(ObjectKind::Schema,None,sc,None,None));}if tv.len()+objects.len()>opt.max_objects{return Err(IntrospectionError::ObjectLimit(tv.len()+objects.len()))}Ok(CatalogSnapshot{dialect:SqlDialect::SqlServer,source_name:spec.safe_source_name(),database_name:spec.database.clone(),tables:tv,objects})
 }
}
