#![forbid(unsafe_code)]
//! Motor do agente autonomo do PhxClaw: planeja, executa com ferramentas sob politica,
//! registra cada passo em evidencia com hash encadeado, roda subagentes em paralelo e
//! dispara tarefas agendadas. Os provedores de modelo e as ferramentas de navegador,
//! busca e documentos entram pelos traits de `phxclaw-agent-core`.

pub mod acao_github;
pub mod acp;
pub mod adaptadores;
pub mod agenda;
pub mod api;
pub mod arquivos;
pub mod avaliacao;
pub mod bateria;
pub mod busca;
pub mod calculadora;
pub mod canais;
pub mod canal;
pub mod canvas;
pub mod chaves;
pub mod checkpoint;
pub mod clima;
pub mod cofres;
pub mod comandos;
pub mod compartilhar;
pub mod config;
pub mod custo;
pub mod dap;
pub mod decisao;
pub mod dispositivos;
pub mod dobras;
pub mod documentos;
pub mod elevenlabs;
pub mod email;
pub mod equipe;
pub mod esquema;
pub mod estilos;
pub mod evolucao;
pub mod ferramentas;
pub mod fidelidade_ui;
pub mod fila;
pub mod fluxo_assistente;
pub mod fluxo_git;
pub mod fluxo_http;
pub mod fluxo_modelos;
pub mod fluxo_politica;
pub mod fluxo_versoes;
pub mod fluxos;
pub mod fluxos_tela;
pub mod forja;
pub mod gatilho_mcp;
pub mod gatilho_poll;
pub mod gatilhos;
pub mod git;
pub mod gonogo;
pub mod gravacao;
pub mod historico;
pub mod hooks;
pub mod ide;
pub mod imagens;
pub mod importar_papeis;
pub mod importar_skills;
pub mod insights;
pub mod instrucoes;
pub mod licenca;
pub mod loja;
pub mod lsp;
pub mod mcp;
pub mod memoria;
pub mod metricas;
pub mod midia;
pub mod montagem;
pub mod motor;
pub mod n8n;
pub mod nanobanana;
pub mod notebook;
pub mod nuvem;
pub mod oauth;
pub mod orcamento;
pub mod otel;
pub mod otimizacao;
pub mod pacotes;
pub mod perguntas;
pub mod pesquisa;
pub mod plugins;
pub mod processo;
pub mod projeto_tarefas;
pub mod pwa;
pub mod python;
pub mod rbac;
pub mod regras;
pub mod remoto;
pub mod repl;
pub mod responsivo_ui;
pub mod revisao;
pub mod rotas;
pub mod roteamento;
pub mod segredos;
pub mod sessoes;
pub mod sincronizar;
pub mod sistema;
pub mod site;
pub mod skills;
pub mod subfluxo;
pub mod tarefa;
pub mod testes;
pub mod tunel;
pub mod ui;
pub mod visao;
pub mod voz;
pub mod voz_memoria;
pub mod workspace;
pub mod xai;

pub use agenda::{Agenda, Schedule};
pub use ferramentas::{
    BackgroundShellTool, EditFileTool, ListFilesTool, ParallelAgentsTool, ReadFileTool,
    ScriptedLlm, ShellTool, WriteFileTool,
};
pub use motor::{Agent, AgentConfig, CancelFlag, NoObserver, Observer};
pub use tarefa::{StepRecord, Task, TaskStatus, TaskStore};
