import { abrir, espera, marca, D, S } from './comum.mjs'; import fs from 'fs';
const { b, p, erros } = await abrir(fs.readFileSync(`${D}/url-a`, 'utf8').trim());
await p.waitForSelector('.vazio');
await p.click('#b-criar'); await p.fill('#f-criar [name=rede]', 'Matriz'); await p.click('#f-criar button.inclui');
await p.waitForSelector('.rede .nome');
await p.click('.rede .acoes button:has-text("Convidar")'); await p.fill('#f-convidar [name=senha]', 'senha-usb-1');
await p.fill('#f-convidar [name=endereco]', '192.168.99.1:51820'); await p.click('#b-gerar');
await p.waitForSelector('#b-copiar:not([hidden])'); marca('codigo', await p.inputValue('#f-convidar [name=codigo]'));
await p.click('#d-convidar [data-fechar]');
await p.click('.rede .acoes button:has-text("Ligar")'); await p.fill('#f-ligar [name=senha]', 'senha-usb-1'); await p.click('#f-ligar button.inclui');
await p.waitForSelector('.lampada.on', { timeout: 20000 });
await espera('b-ligada'); await p.waitForSelector('.membro .ponto.on', { timeout: 30000 });
await p.click('.rede .acoes button:has-text("USB")');
await p.waitForSelector('#usb-locais .usb-linha');
await p.screenshot({ path: `${S}/u1-a-antes.png` });
await p.click('#usb-locais button:has-text("Compartilhar")');
await p.waitForSelector('#usb-locais button:has-text("Parar")');
console.log('A rodape:', await p.textContent('#rodape'));
marca('a-compartilhou'); await espera('kernel-bind');
await p.click('#d-usb [data-fechar]'); await p.click('.rede .acoes button:has-text("USB")');
await p.waitForSelector('#usb-locais .marca');
await p.screenshot({ path: `${S}/u2-a-compartilhado.png` });
console.log('A marca:', await p.textContent('#usb-locais .marca'));
await espera('b-fim', 120000);
console.log('A erros', JSON.stringify(erros)); await b.close();
