import { abrir, espera, marca, D, S } from './comum.mjs'; import fs from 'fs';
await espera('codigo');
const { b, p, erros } = await abrir(fs.readFileSync(`${D}/url-b`, 'utf8').trim());
await p.click('#b-entrar'); await p.fill('#f-entrar [name=codigo]', fs.readFileSync(`${D}/codigo`, 'utf8'));
await p.fill('#f-entrar [name=senha]', 'senha-usb-1'); await p.click('#f-entrar button.inclui');
await p.waitForSelector('.rede .nome');
await p.click('.rede .acoes button:has-text("Ligar")'); await p.fill('#f-ligar [name=senha]', 'senha-usb-1'); await p.click('#f-ligar button.inclui');
await p.waitForSelector('.lampada.on', { timeout: 20000 }); marca('b-ligada');
await p.waitForSelector('.membro .ponto.on', { timeout: 30000 });
await espera('kernel-bind');
await p.click('.rede .acoes button:has-text("USB")');
await p.waitForSelector('#usb-membros button:has-text("Ver USB")');
await p.click('#usb-membros button:has-text("Ver USB")');
await p.waitForSelector('#usb-membros .usb-sub .usb-linha', { timeout: 15000 });
await p.screenshot({ path: `${S}/u3-b-remotos.png` });
await p.click('#usb-membros button:has-text("Usar")');
await p.waitForFunction(() => /anexado/.test(document.querySelector('#rodape').textContent) || document.querySelector('#f-usb .msg').textContent, null, { timeout: 15000 });
console.log('B rodape:', await p.textContent('#rodape'), '| msg:', await p.textContent('#f-usb .msg'));
marca('b-usou'); await espera('kernel-attach');
await p.click('#d-usb [data-fechar]'); await p.click('.rede .acoes button:has-text("USB")');
await p.waitForSelector('#usb-portas button:has-text("Soltar")');
await p.screenshot({ path: `${S}/u4-b-em-uso.png` });
await p.click('#usb-portas button:has-text("Soltar")');
await p.waitForFunction(() => /solta/.test(document.querySelector('#rodape').textContent), null, { timeout: 10000 });
console.log('B rodape:', await p.textContent('#rodape'));
console.log('B erros', JSON.stringify(erros)); marca('b-fim'); await b.close();
