use async_trait::async_trait;
use phx_sql_introspection_api::*;
use phx_sql_model::{ObjectKind, Partitioning, TableStatistics};
use phx_sql_parser_api::SqlDialect;
use sqlx::{postgres::{PgConnectOptions, PgPoolOptions, PgSslMode}, Row};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::time::Duration;

pub struct PostgreSqlIntrospector;

fn allowed_schema(schema:&str,opt:&IntrospectionOptions)->bool{
    if !opt.schemas.is_empty()&&!opt.schemas.iter().any(|s|s.eq_ignore_ascii_case(schema)){return false}
    opt.include_system||!matches!(schema,"pg_catalog"|"information_schema"|"pg_toast")
}
fn empty_table(schema:String,name:String)->CatalogTable{CatalogTable{schema,name,columns:vec![],primary_key:vec![],foreign_keys:vec![],check_constraints:vec![],partitioning:None,statistics:None,definition:None}}
fn obj(kind:ObjectKind,schema:Option<String>,name:String,target:Option<String>,definition:Option<String>)->CatalogObject{CatalogObject{kind,schema,name,target,definition,metadata:BTreeMap::new()}}
fn strip_check(s:String)->String{let x=s.trim();if x.to_ascii_uppercase().starts_with("CHECK (")&&x.ends_with(')'){x[7..x.len()-1].to_string()}else{x.to_string()}}

#[async_trait]
impl DatabaseIntrospector for PostgreSqlIntrospector{
 fn dialect(&self)->SqlDialect{SqlDialect::PostgreSql}
 async fn introspect(&self,spec:&ConnectionSpec,options:&IntrospectionOptions)->Result<CatalogSnapshot,IntrospectionError>{
  if spec.dialect!=SqlDialect::PostgreSql{return Err(IntrospectionError::UnsupportedDialect(spec.dialect.as_str().into()))}
  let ssl=match spec.tls{TlsMode::Disable=>PgSslMode::Disable,TlsMode::Prefer=>PgSslMode::Prefer,TlsMode::Require=>PgSslMode::Require};
  let mut conn=PgConnectOptions::new().host(&spec.host).port(spec.port.unwrap_or(5432)).database(&spec.database).ssl_mode(ssl);
  if let Some(u)=&spec.username{conn=conn.username(u)}if let Some(p)=&spec.password{conn=conn.password(p)}
  let pool=PgPoolOptions::new().max_connections(2).acquire_timeout(Duration::from_secs(12)).connect_with(conn).await.map_err(|e|IntrospectionError::Connection(e.to_string()))?;
  let rows=sqlx::query(r#"SELECT c.table_schema,c.table_name,c.column_name,COALESCE(NULLIF(c.data_type,'USER-DEFINED'),c.udt_name) data_type,c.is_nullable,c.column_default,c.ordinal_position,c.is_generated,c.generation_expression FROM information_schema.columns c JOIN information_schema.tables t ON t.table_schema=c.table_schema AND t.table_name=c.table_name WHERE t.table_type='BASE TABLE' ORDER BY c.table_schema,c.table_name,c.ordinal_position"#).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut tables:HashMap<(String,String),CatalogTable>=HashMap::new();
  for r in rows{let s:String=r.try_get("table_schema").unwrap_or_default();if !allowed_schema(&s,options){continue}let t:String=r.try_get("table_name").unwrap_or_default();let key=(s.to_ascii_lowercase(),t.to_ascii_lowercase());let e=tables.entry(key).or_insert_with(||empty_table(s.clone(),t.clone()));let gen:Option<String>=r.try_get("generation_expression").ok();let isgen=r.try_get::<String,_>("is_generated").unwrap_or_default();e.columns.push(CatalogColumn{name:r.try_get("column_name").unwrap_or_default(),data_type:r.try_get("data_type").unwrap_or_else(|_|"unknown".into()),nullable:r.try_get::<String,_>("is_nullable").unwrap_or_default()=="YES",default_expr:r.try_get("column_default").ok(),primary_key:false,unique:false,ordinal:r.try_get::<i32,_>("ordinal_position").unwrap_or(0).max(0)as usize,generated_expression:gen,generated_kind:if isgen.eq_ignore_ascii_case("ALWAYS"){Some("stored".into())}else{None}});}
  if tables.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(tables.len()))}

  let pk=sqlx::query("SELECT tc.table_schema,tc.table_name,kcu.column_name,kcu.ordinal_position FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON kcu.constraint_schema=tc.constraint_schema AND kcu.constraint_name=tc.constraint_name WHERE tc.constraint_type='PRIMARY KEY' ORDER BY tc.table_schema,tc.table_name,kcu.ordinal_position").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut pks:HashMap<(String,String),Vec<(usize,String)>>=HashMap::new();for r in pk{let s:String=r.try_get("table_schema").unwrap_or_default();if !allowed_schema(&s,options){continue}let t:String=r.try_get("table_name").unwrap_or_default();pks.entry((s.to_ascii_lowercase(),t.to_ascii_lowercase())).or_default().push((r.try_get::<i32,_>("ordinal_position").unwrap_or(0).max(0)as usize,r.try_get("column_name").unwrap_or_default()));}let primary:HashMap<_,_>=pks.into_iter().map(|(k,mut v)|{v.sort_by_key(|x|x.0);(k,v.into_iter().map(|x|x.1).collect())}).collect();
  let uq=sqlx::query("SELECT tc.table_schema,tc.table_name,tc.constraint_name,kcu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON kcu.constraint_schema=tc.constraint_schema AND kcu.constraint_name=tc.constraint_name WHERE tc.constraint_type='UNIQUE'").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut groups:HashMap<(String,String,String),Vec<String>>=HashMap::new();for r in uq{let s:String=r.try_get("table_schema").unwrap_or_default();if !allowed_schema(&s,options){continue}let t:String=r.try_get("table_name").unwrap_or_default();groups.entry((s.to_ascii_lowercase(),t.to_ascii_lowercase(),r.try_get("constraint_name").unwrap_or_default())).or_default().push(r.try_get("column_name").unwrap_or_default());}let mut uniques:HashMap<(String,String),BTreeSet<String>>=HashMap::new();for((s,t,_),c)in groups{if c.len()==1{uniques.entry((s,t)).or_default().insert(c[0].to_ascii_lowercase());}}

  let fk=sqlx::query(r#"SELECT tc.constraint_name,tc.table_schema,tc.table_name,kcu.column_name,kcu.ordinal_position,kcu2.table_schema foreign_table_schema,kcu2.table_name foreign_table_name,kcu2.column_name foreign_column_name,rc.delete_rule FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON kcu.constraint_schema=tc.constraint_schema AND kcu.constraint_name=tc.constraint_name JOIN information_schema.referential_constraints rc ON rc.constraint_schema=tc.constraint_schema AND rc.constraint_name=tc.constraint_name JOIN information_schema.key_column_usage kcu2 ON kcu2.constraint_schema=rc.unique_constraint_schema AND kcu2.constraint_name=rc.unique_constraint_name AND kcu2.ordinal_position=kcu.position_in_unique_constraint WHERE tc.constraint_type='FOREIGN KEY' ORDER BY tc.table_schema,tc.table_name,tc.constraint_name,kcu.ordinal_position"#).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  #[derive(Default)]struct F{fs:String,ft:String,ts:String,tt:String,a:Vec<(usize,String)>,b:Vec<(usize,String)>,del:Option<String>,name:String}let mut fgs:HashMap<String,F>=HashMap::new();for r in fk{let fs:String=r.try_get("table_schema").unwrap_or_default();if !allowed_schema(&fs,options){continue}let ft:String=r.try_get("table_name").unwrap_or_default();let n:String=r.try_get("constraint_name").unwrap_or_default();let g=fgs.entry(format!("{fs}.{ft}:{n}")).or_default();g.fs=fs;g.ft=ft;g.ts=r.try_get("foreign_table_schema").unwrap_or_default();g.tt=r.try_get("foreign_table_name").unwrap_or_default();g.name=n;let o=r.try_get::<i32,_>("ordinal_position").unwrap_or(0).max(0)as usize;g.a.push((o,r.try_get("column_name").unwrap_or_default()));g.b.push((o,r.try_get("foreign_column_name").unwrap_or_default()));g.del=r.try_get("delete_rule").ok();}for(_,mut g)in fgs{g.a.sort_by_key(|x|x.0);g.b.sort_by_key(|x|x.0);let fk=CatalogForeignKey{constraint_name:Some(g.name),from_schema:g.fs.clone(),from_table:g.ft.clone(),from_columns:g.a.into_iter().map(|x|x.1).collect(),to_schema:g.ts,to_table:g.tt,to_columns:g.b.into_iter().map(|x|x.1).collect(),on_delete:g.del};if let Some(t)=tables.get_mut(&(g.fs.to_ascii_lowercase(),g.ft.to_ascii_lowercase())){t.foreign_keys.push(fk)}}

  let checks=sqlx::query("SELECT n.nspname schema_name,c.relname table_name,con.conname constraint_name,pg_get_constraintdef(con.oid,true) definition FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE con.contype='c' ORDER BY n.nspname,c.relname,con.conname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;for r in checks{let s:String=r.try_get("schema_name").unwrap_or_default();if !allowed_schema(&s,options){continue}let t:String=r.try_get("table_name").unwrap_or_default();if let Some(tab)=tables.get_mut(&(s.to_ascii_lowercase(),t.to_ascii_lowercase())){tab.check_constraints.push(CatalogCheckConstraint{name:r.try_get("constraint_name").ok(),expression:strip_check(r.try_get("definition").unwrap_or_default()),column:None});}}

  if options.include_statistics{let stats=sqlx::query("SELECT n.nspname schema_name,c.relname table_name,c.reltuples::bigint estimated_rows,c.relkind,CASE WHEN c.relkind='p' THEN NULL ELSE pg_table_size(c.oid)::bigint END data_bytes,CASE WHEN c.relkind='p' THEN NULL ELSE pg_indexes_size(c.oid)::bigint END index_bytes,CASE WHEN c.relkind='p' THEN NULL ELSE pg_total_relation_size(c.oid)::bigint END total_bytes,CASE WHEN c.relkind='p' THEN pg_get_partkeydef(c.oid) ELSE NULL END partkey FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p')").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;for r in stats{let s:String=r.try_get("schema_name").unwrap_or_default();if !allowed_schema(&s,options){continue}let t:String=r.try_get("table_name").unwrap_or_default();if let Some(tab)=tables.get_mut(&(s.to_ascii_lowercase(),t.to_ascii_lowercase())){let rows=r.try_get::<i64,_>("estimated_rows").ok().filter(|v|*v>=0).map(|v|v as u64);let db=r.try_get::<i64,_>("data_bytes").ok().filter(|v|*v>=0).map(|v|v as u64);let ib=r.try_get::<i64,_>("index_bytes").ok().filter(|v|*v>=0).map(|v|v as u64);let tb=r.try_get::<i64,_>("total_bytes").ok().filter(|v|*v>=0).map(|v|v as u64);tab.statistics=Some(TableStatistics{estimated_rows:rows,data_bytes:db,index_bytes:ib,total_bytes:tb});if let Ok(k)=r.try_get::<String,_>("partkey"){if !k.is_empty(){tab.partitioning=Some(Partitioning{kind:k.split_whitespace().next().unwrap_or("partition").to_ascii_lowercase(),expression:Some(k),parent:None,bound:None});}}}}
  }
  let mut tv=tables.into_values().collect::<Vec<_>>();tv.sort_by(|a,b|(&a.schema,&a.name).cmp(&(&b.schema,&b.name)));apply_key_flags(&mut tv,&primary,&uniques);

  let mut objects=Vec::new();
  if options.include_views{for r in sqlx::query("SELECT table_schema,table_name,view_definition FROM information_schema.views ORDER BY table_schema,table_name").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("table_schema").unwrap_or_default();if allowed_schema(&s,options){objects.push(obj(ObjectKind::View,Some(s),r.try_get("table_name").unwrap_or_default(),None,r.try_get("view_definition").ok()));}}}
  if options.include_indexes{for r in sqlx::query("SELECT schemaname,tablename,indexname,indexdef FROM pg_indexes ORDER BY schemaname,tablename,indexname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("schemaname").unwrap_or_default();if allowed_schema(&s,options){let t:String=r.try_get("tablename").unwrap_or_default();objects.push(obj(ObjectKind::Index,Some(s.clone()),r.try_get("indexname").unwrap_or_default(),Some(format!("{s}.{t}")),r.try_get("indexdef").ok()));}}}
  if options.include_routines{for r in sqlx::query("SELECT routine_schema,routine_name,routine_definition FROM information_schema.routines ORDER BY routine_schema,routine_name").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("routine_schema").unwrap_or_default();if allowed_schema(&s,options){objects.push(obj(ObjectKind::Function,Some(s),r.try_get("routine_name").unwrap_or_default(),None,r.try_get("routine_definition").ok()));}}}
  if options.include_triggers{for r in sqlx::query("SELECT trigger_schema,trigger_name,event_object_schema,event_object_table,action_statement FROM information_schema.triggers ORDER BY trigger_schema,trigger_name").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("trigger_schema").unwrap_or_default();if allowed_schema(&s,options){let ts:String=r.try_get("event_object_schema").unwrap_or_default();let tt:String=r.try_get("event_object_table").unwrap_or_default();objects.push(obj(ObjectKind::Trigger,Some(s),r.try_get("trigger_name").unwrap_or_default(),Some(format!("{ts}.{tt}")),r.try_get("action_statement").ok()));}}}
  if options.include_policies{for r in sqlx::query("SELECT schemaname,tablename,policyname,qual,with_check FROM pg_policies ORDER BY schemaname,tablename,policyname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("schemaname").unwrap_or_default();if allowed_schema(&s,options){let t:String=r.try_get("tablename").unwrap_or_default();objects.push(obj(ObjectKind::Policy,Some(s.clone()),r.try_get("policyname").unwrap_or_default(),Some(format!("{s}.{t}")),Some(format!("USING ({}) WITH CHECK ({})",r.try_get::<String,_>("qual").unwrap_or_default(),r.try_get::<String,_>("with_check").unwrap_or_default()))));}}}
  if options.include_advanced_objects{
   for r in sqlx::query("SELECT schemaname,matviewname,definition FROM pg_matviews ORDER BY schemaname,matviewname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("schemaname").unwrap_or_default();if allowed_schema(&s,options){objects.push(obj(ObjectKind::MaterializedView,Some(s),r.try_get("matviewname").unwrap_or_default(),None,r.try_get("definition").ok()));}}
   for r in sqlx::query("SELECT n.nspname schema_name,c.relname sequence_name FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='S' ORDER BY n.nspname,c.relname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("schema_name").unwrap_or_default();if allowed_schema(&s,options){objects.push(obj(ObjectKind::Sequence,Some(s),r.try_get("sequence_name").unwrap_or_default(),None,None));}}
   for r in sqlx::query("SELECT e.extname,n.nspname schema_name,e.extversion,e.extrelocatable FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace ORDER BY e.extname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let mut o=obj(ObjectKind::Extension,None,r.try_get("extname").unwrap_or_default(),None,None);o.metadata.insert("schema".into(),r.try_get::<String,_>("schema_name").unwrap_or_default());o.metadata.insert("version".into(),r.try_get::<String,_>("extversion").unwrap_or_default());o.metadata.insert("relocatable".into(),r.try_get::<bool,_>("extrelocatable").unwrap_or(false).to_string());objects.push(o);}
   for r in sqlx::query("SELECT cn.nspname child_schema,c.relname child_name,pn.nspname parent_schema,p.relname parent_name,pg_get_expr(c.relpartbound,c.oid,true) bound FROM pg_inherits i JOIN pg_class c ON c.oid=i.inhrelid JOIN pg_namespace cn ON cn.oid=c.relnamespace JOIN pg_class p ON p.oid=i.inhparent JOIN pg_namespace pn ON pn.oid=p.relnamespace ORDER BY cn.nspname,c.relname").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{let s:String=r.try_get("child_schema").unwrap_or_default();if allowed_schema(&s,options){let ps:String=r.try_get("parent_schema").unwrap_or_default();let pn:String=r.try_get("parent_name").unwrap_or_default();let mut o=obj(ObjectKind::Partition,Some(s),r.try_get("child_name").unwrap_or_default(),Some(format!("{ps}.{pn}")),None);o.metadata.insert("bound".into(),r.try_get::<String,_>("bound").unwrap_or_default());objects.push(o);}}
  }
  let schemas:BTreeSet<_>=tv.iter().map(|t|t.schema.clone()).collect();for s in schemas{objects.push(obj(ObjectKind::Schema,None,s,None,None));}
  if tv.len()+objects.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(tv.len()+objects.len()))}
  Ok(CatalogSnapshot{dialect:SqlDialect::PostgreSql,source_name:spec.safe_source_name(),database_name:spec.database.clone(),tables:tv,objects})
 }
}
