//! Os textos do PhxZipCmd, nos seis idiomas -- a TABELA. O motor que resolve
//! (idioma pedido, queda para o portugues, `{marcadores}`) e o do
//! `phxsql_core::idiomas`, o mesmo do servidor: aqui so moram as linhas.
//!
//! Mora num arquivo separado do `lib.rs` de proposito: o laco de chaves varre
//! o `lib.rs` atras de `"zipcmd.` -- com a tabela dentro dele, toda chave se
//! contaria como pedida por ela mesma, e chave morta nunca apareceria.
//!
//! O que NAO e texto e fica fora: nome de opcao (`--destino`), nome de
//! comando (`listar`), nome de variavel (`PHXZIP_SENHA`) e o nome estavel do
//! erro do motor (`[DESTINO_INSEGURO]`). Sao protocolo -- traduzi-los quebraria
//! o script de quem os digita. A frase do erro do MOTOR (`phxzip`) continua no
//! idioma em que o motor a escreveu, como a parte variavel do servidor.
//!
//! Ordem das colunas: Portugues, Frances, Ingles, Italiano, Alemao, Espanhol.

use phxsql_core::idiomas::TextoDeFabrica;
use phxsql_core::texto;

/// O prefixo de toda chave desta tabela.
pub const PREFIXO: &str = "zipcmd.";

#[rustfmt::skip]
pub const FABRICA: &[TextoDeFabrica] = &[
    // ------------------------------------------------------------ o --help
    texto!("zipcmd.uso_titulo",
        "phxzipcmd -- o PhxZip no terminal (formato 7z: Copy, LZMA, LZMA2 e 7zAES)",
        "phxzipcmd -- PhxZip dans le terminal (format 7z : Copy, LZMA, LZMA2 et 7zAES)",
        "phxzipcmd -- PhxZip in the terminal (7z format: Copy, LZMA, LZMA2 and 7zAES)",
        "phxzipcmd -- PhxZip nel terminale (formato 7z: Copy, LZMA, LZMA2 e 7zAES)",
        "phxzipcmd -- PhxZip im Terminal (7z-Format: Copy, LZMA, LZMA2 und 7zAES)",
        "phxzipcmd -- PhxZip en el terminal (formato 7z: Copy, LZMA, LZMA2 y 7zAES)"),
    texto!("zipcmd.uso_comandos",
        "USO:\n  phxzipcmd listar    ARQUIVO.7z [--confiavel]\n  phxzipcmd testar    ARQUIVO.7z [--confiavel]\n  phxzipcmd extrair   ARQUIVO.7z [--destino PASTA] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARQUIVO.7z CAMINHO... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version",
        "USAGE :\n  phxzipcmd listar    ARCHIVE.7z [--confiavel]\n  phxzipcmd testar    ARCHIVE.7z [--confiavel]\n  phxzipcmd extrair   ARCHIVE.7z [--destino DOSSIER] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARCHIVE.7z CHEMIN... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version",
        "USAGE:\n  phxzipcmd listar    ARCHIVE.7z [--confiavel]\n  phxzipcmd testar    ARCHIVE.7z [--confiavel]\n  phxzipcmd extrair   ARCHIVE.7z [--destino FOLDER] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARCHIVE.7z PATH... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version",
        "USO:\n  phxzipcmd listar    ARCHIVIO.7z [--confiavel]\n  phxzipcmd testar    ARCHIVIO.7z [--confiavel]\n  phxzipcmd extrair   ARCHIVIO.7z [--destino CARTELLA] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARCHIVIO.7z PERCORSO... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version",
        "AUFRUF:\n  phxzipcmd listar    ARCHIV.7z [--confiavel]\n  phxzipcmd testar    ARCHIV.7z [--confiavel]\n  phxzipcmd extrair   ARCHIV.7z [--destino ORDNER] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARCHIV.7z PFAD... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version",
        "USO:\n  phxzipcmd listar    ARCHIVO.7z [--confiavel]\n  phxzipcmd testar    ARCHIVO.7z [--confiavel]\n  phxzipcmd extrair   ARCHIVO.7z [--destino CARPETA] [--sobrescrever] [--confiavel]\n  phxzipcmd compactar ARCHIVO.7z RUTA... [--copia] [--sobrescrever]\n                      [--cifrar [--nomes-claros] [--ciclos N]]\n  phxzipcmd --help | --version"),
    texto!("zipcmd.uso_senha",
        "A SENHA NUNCA VEM POR ARGUMENTO. --senha, --password, --pass, --pwd, -p (em\nqualquer caixa, com ou sem = ou :) sao recusados: o argumento aparece no `ps`\nde qualquer usuario e fica no historico do shell. Ela vem, nesta ordem:\n  1. da variavel {var};\n  2. da entrada padrao: num terminal e perguntada SEM ECO (o /bin/stty desliga,\n     e o eco volta no fim, no ctrl+D e no ctrl+C); num cano, e a primeira\n     linha (ate {teto} bytes).",
        "LE MOT DE PASSE NE VIENT JAMAIS EN ARGUMENT. --senha, --password, --pass, --pwd, -p\n(quelle que soit la casse, avec ou sans = ou :) sont refusés : l'argument apparaît\ndans le `ps` de tout utilisateur et reste dans l'historique du shell. Il vient,\ndans cet ordre :\n  1. de la variable {var} ;\n  2. de l'entrée standard : dans un terminal, il est demandé SANS ÉCHO (/bin/stty\n     le coupe, et l'écho revient à la fin, au ctrl+D et au ctrl+C) ; dans un tube,\n     c'est la première ligne (jusqu'à {teto} octets).",
        "THE PASSWORD NEVER COMES AS AN ARGUMENT. --senha, --password, --pass, --pwd, -p (in\nany case, with or without = or :) are refused: the argument shows up in `ps` for\nevery user and stays in the shell history. It comes, in this order:\n  1. from the variable {var};\n  2. from standard input: on a terminal it is asked WITHOUT ECHO (/bin/stty turns\n     it off, and echo comes back at the end, on ctrl+D and on ctrl+C); from a\n     pipe, it is the first line (up to {teto} bytes).",
        "LA PASSWORD NON ARRIVA MAI COME ARGOMENTO. --senha, --password, --pass, --pwd, -p\n(maiuscole o minuscole, con o senza = o :) sono rifiutati: l'argomento compare nel\n`ps` di qualsiasi utente e resta nella cronologia della shell. Arriva, in quest'ordine:\n  1. dalla variabile {var};\n  2. dall'input standard: in un terminale è chiesta SENZA ECO (/bin/stty lo spegne,\n     e l'eco torna alla fine, con ctrl+D e con ctrl+C); da una pipe, è la prima\n     riga (fino a {teto} byte).",
        "DAS PASSWORT KOMMT NIE ALS ARGUMENT. --senha, --password, --pass, --pwd, -p (in\nbeliebiger Schreibweise, mit oder ohne = oder :) werden abgelehnt: das Argument\nerscheint in `ps` für jeden Benutzer und bleibt im Shell-Verlauf. Es kommt, in\ndieser Reihenfolge:\n  1. aus der Variablen {var};\n  2. aus der Standardeingabe: im Terminal wird es OHNE ECHO abgefragt (/bin/stty\n     schaltet es ab, und das Echo kommt am Ende, bei Strg+D und bei Strg+C zurück);\n     aus einer Pipe ist es die erste Zeile (bis {teto} Bytes).",
        "LA CONTRASEÑA NUNCA VIENE POR ARGUMENTO. --senha, --password, --pass, --pwd, -p\n(en mayúsculas o minúsculas, con o sin = o :) se rechazan: el argumento aparece en\nel `ps` de cualquier usuario y queda en el historial del shell. Viene, en este orden:\n  1. de la variable {var};\n  2. de la entrada estándar: en un terminal se pide SIN ECO (/bin/stty lo apaga,\n     y el eco vuelve al final, con ctrl+D y con ctrl+C); por una tubería, es la\n     primera línea (hasta {teto} bytes)."),
    texto!("zipcmd.uso_hifen",
        "CAMINHO QUE COMECA COM HIFEN vai com ./ na frente: ./-planilhas, e nao\n-planilhas (que seria lido como opcao, e -p... como senha por argumento).",
        "UN CHEMIN QUI COMMENCE PAR UN TIRET prend ./ devant : ./-tableaux, et non\n-tableaux (qui serait lu comme une option, et -p... comme un mot de passe en argument).",
        "A PATH STARTING WITH A HYPHEN takes ./ in front: ./-sheets, not\n-sheets (which would be read as an option, and -p... as a password argument).",
        "UN PERCORSO CHE INIZIA CON IL TRATTINO va con ./ davanti: ./-fogli, e non\n-fogli (che sarebbe letto come opzione, e -p... come password per argomento).",
        "EIN PFAD, DER MIT BINDESTRICH BEGINNT, bekommt ./ davor: ./-tabellen, nicht\n-tabellen (das würde als Option gelesen, und -p... als Passwort-Argument).",
        "UNA RUTA QUE EMPIEZA CON GUION va con ./ delante: ./-planillas, y no\n-planillas (que se leería como opción, y -p... como contraseña por argumento)."),
    texto!("zipcmd.uso_exemplos",
        "  {var}='a senha' phxzipcmd extrair copia.7z --destino saida\n  phxzipcmd compactar copia.7z docs --cifrar < arquivo-da-senha",
        "  {var}='le mot de passe' phxzipcmd extrair copie.7z --destino sortie\n  phxzipcmd compactar copie.7z docs --cifrar < fichier-du-mot-de-passe",
        "  {var}='the password' phxzipcmd extrair backup.7z --destino out\n  phxzipcmd compactar backup.7z docs --cifrar < password-file",
        "  {var}='la password' phxzipcmd extrair copia.7z --destino uscita\n  phxzipcmd compactar copia.7z docs --cifrar < file-della-password",
        "  {var}='das Passwort' phxzipcmd extrair sicherung.7z --destino ausgabe\n  phxzipcmd compactar sicherung.7z docs --cifrar < passwort-datei",
        "  {var}='la contraseña' phxzipcmd extrair copia.7z --destino salida\n  phxzipcmd compactar copia.7z docs --cifrar < archivo-de-la-contraseña"),
    texto!("zipcmd.uso_extracao",
        "A EXTRACAO NUNCA SAI DA PASTA DE DESTINO E NUNCA SEGUE LINK. Entrada marcada\ncomo link simbolico vira arquivo comum, com aviso; pasta do destino que e\nlink recusa a entrada. Arquivo que ja existe recusa, a menos que venha\n--sobrescrever (e ai o que se apaga e o arquivo ou o link, nunca o alvo).",
        "L'EXTRACTION NE SORT JAMAIS DU DOSSIER DE DESTINATION ET NE SUIT JAMAIS DE LIEN.\nUne entrée marquée comme lien symbolique devient un fichier ordinaire, avec un\navertissement ; un dossier de destination qui est un lien refuse l'entrée. Un\nfichier qui existe déjà refuse, sauf avec --sobrescrever (et alors ce qui est\nsupprimé est le fichier ou le lien, jamais la cible).",
        "EXTRACTION NEVER LEAVES THE DESTINATION FOLDER AND NEVER FOLLOWS LINKS. An entry\nmarked as a symbolic link becomes a regular file, with a warning; a destination\nfolder that is a link refuses the entry. A file that already exists refuses,\nunless --sobrescrever comes (and then what is removed is the file or the link,\nnever the target).",
        "L'ESTRAZIONE NON ESCE MAI DALLA CARTELLA DI DESTINAZIONE E NON SEGUE MAI I LINK.\nUna voce marcata come link simbolico diventa un file normale, con avviso; una\ncartella di destinazione che è un link rifiuta la voce. Un file che esiste già\nrifiuta, a meno che venga --sobrescrever (e allora si cancella il file o il link,\nmai la destinazione).",
        "DAS ENTPACKEN VERLÄSST NIE DEN ZIELORDNER UND FOLGT NIE EINEM LINK. Ein als\nsymbolischer Link markierter Eintrag wird mit Warnung zur normalen Datei; ein\nZielordner, der ein Link ist, lehnt den Eintrag ab. Eine bereits vorhandene Datei\nlehnt ab, außer mit --sobrescrever (und dann wird die Datei oder der Link\ngelöscht, nie das Ziel).",
        "LA EXTRACCIÓN NUNCA SALE DE LA CARPETA DE DESTINO Y NUNCA SIGUE ENLACES. Una\nentrada marcada como enlace simbólico se vuelve archivo común, con aviso; una\ncarpeta de destino que es enlace rechaza la entrada. Un archivo que ya existe se\nrechaza, salvo que venga --sobrescrever (y entonces lo que se borra es el archivo\no el enlace, nunca el destino)."),
    texto!("zipcmd.uso_pasta_alheia",
        "Nenhuma pasta do caminho pode aceitar escrita de outro usuario (nem ser\ndele): ele poderia trocar uma pasta por um link no meio da extracao. Extraia\nnuma pasta sua. Conteudo que veio cifrado nasce com permissao 0600.",
        "Aucun dossier du chemin ne peut accepter l'écriture d'un autre utilisateur (ni\nlui appartenir) : il pourrait remplacer un dossier par un lien au milieu de\nl'extraction. Extrayez dans un dossier à vous. Le contenu chiffré naît avec la\npermission 0600.",
        "No folder on the path may accept writes from another user (nor belong to\nthem): they could swap a folder for a link in the middle of the extraction.\nExtract into a folder of your own. Content that came encrypted is created 0600.",
        "Nessuna cartella del percorso può accettare scritture da un altro utente (né\nessere sua): potrebbe scambiare una cartella con un link a metà estrazione.\nEstrai in una cartella tua. Il contenuto arrivato cifrato nasce con permesso 0600.",
        "Kein Ordner im Pfad darf Schreibzugriff anderer Benutzer erlauben (oder ihnen\ngehören): sie könnten mitten im Entpacken einen Ordner gegen einen Link tauschen.\nEntpacken Sie in einen eigenen Ordner. Verschlüsselt gelieferter Inhalt entsteht\nmit Recht 0600.",
        "Ninguna carpeta de la ruta puede aceptar escritura de otro usuario (ni ser\nsuya): podría cambiar una carpeta por un enlace en medio de la extracción.\nExtraiga en una carpeta suya. El contenido que vino cifrado nace con permiso 0600."),
    texto!("zipcmd.uso_compactacao",
        "A COMPACTACAO NAO SEGUE LINK: link e arquivo especial sao pulados, com aviso,\ne arquivo trocado por link durante a leitura aborta. O .7z nasce 0600.",
        "LA COMPRESSION NE SUIT PAS LES LIENS : liens et fichiers spéciaux sont ignorés,\navec avertissement, et un fichier remplacé par un lien pendant la lecture fait\navorter. Le .7z naît en 0600.",
        "COMPRESSION DOES NOT FOLLOW LINKS: links and special files are skipped, with a\nwarning, and a file swapped for a link while being read aborts. The .7z is\ncreated 0600.",
        "LA COMPRESSIONE NON SEGUE I LINK: link e file speciali sono saltati, con avviso,\ne un file scambiato con un link durante la lettura interrompe. Il .7z nasce 0600.",
        "DAS KOMPRIMIEREN FOLGT KEINEM LINK: Links und Spezialdateien werden mit Warnung\nübersprungen, und eine während des Lesens gegen einen Link getauschte Datei\nbricht ab. Das .7z entsteht mit 0600.",
        "LA COMPRESIÓN NO SIGUE ENLACES: enlaces y archivos especiales se saltan, con\naviso, y un archivo cambiado por un enlace durante la lectura aborta. El .7z\nnace 0600."),
    texto!("zipcmd.uso_confiavel",
        "--confiavel abre com a folga do 7-Zip (ciclos ate 24, sem o teto de 1 GiB do\narquivo nem o de 4 GiB da soma descompactada). Use so para arquivo que voce\nmesmo gravou.",
        "--confiavel ouvre avec la marge de 7-Zip (cycles jusqu'à 24, sans le plafond de\n1 Gio de l'archive ni celui de 4 Gio de la somme décompressée). À n'utiliser que\npour une archive que vous avez écrite vous-même.",
        "--confiavel opens with 7-Zip's slack (cycles up to 24, without the 1 GiB cap on\nthe archive nor the 4 GiB cap on the uncompressed total). Use it only for an\narchive you wrote yourself.",
        "--confiavel apre con il margine di 7-Zip (cicli fino a 24, senza il tetto di\n1 GiB dell'archivio né quello di 4 GiB della somma decompressa). Usalo solo per\nun archivio scritto da te.",
        "--confiavel öffnet mit dem Spielraum von 7-Zip (Zyklen bis 24, ohne die Grenze\nvon 1 GiB für das Archiv und von 4 GiB für die entpackte Summe). Nur für ein\nselbst geschriebenes Archiv verwenden.",
        "--confiavel abre con la holgura de 7-Zip (ciclos hasta 24, sin el tope de 1 GiB\ndel archivo ni el de 4 GiB de la suma descomprimida). Úselo solo para un archivo\nque usted mismo grabó."),
    texto!("zipcmd.uso_idioma",
        "IDIOMA: a variavel {var} (pt, fr, en, it, de, es, ou o nome: Ingles) e, sem\nela, o LANG do sistema. Idioma desconhecido fala portugues.",
        "LANGUE : la variable {var} (pt, fr, en, it, de, es, ou le nom : Frances) et, à\ndéfaut, le LANG du système. Une langue inconnue parle portugais.",
        "LANGUAGE: the variable {var} (pt, fr, en, it, de, es, or the name: Ingles) and,\nwithout it, the system LANG. An unknown language speaks Portuguese.",
        "LINGUA: la variabile {var} (pt, fr, en, it, de, es, o il nome: Italiano) e, in\nsua assenza, il LANG del sistema. Una lingua sconosciuta parla portoghese.",
        "SPRACHE: die Variable {var} (pt, fr, en, it, de, es oder der Name: Alemao) und,\nohne sie, das LANG des Systems. Eine unbekannte Sprache spricht Portugiesisch.",
        "IDIOMA: la variable {var} (pt, fr, en, it, de, es, o el nombre: Espanhol) y, sin\nella, el LANG del sistema. Un idioma desconocido habla portugués."),
    texto!("zipcmd.uso_saida",
        "SAIDA: 0 deu certo; 1 a operacao falhou; 2 uso errado.",
        "SORTIE : 0 réussi ; 1 l'opération a échoué ; 2 mauvais usage.",
        "EXIT: 0 success; 1 the operation failed; 2 wrong usage.",
        "USCITA: 0 riuscito; 1 l'operazione è fallita; 2 uso errato.",
        "EXIT-CODE: 0 erfolgreich; 1 Vorgang fehlgeschlagen; 2 falscher Aufruf.",
        "SALIDA: 0 salió bien; 1 la operación falló; 2 uso incorrecto."),

    // ------------------------------------------------------------ a senha
    texto!("zipcmd.senha_por_argumento",
        "{opcao} recusado -- a senha nunca vem por argumento, porque o argumento aparece no `ps` de qualquer usuario e fica no historico do shell.\nUse a variavel {var}, ou deixe o phxzipcmd perguntar (sem eco), ou mande a senha pela entrada padrao: phxzipcmd ... < arquivo-da-senha",
        "{opcao} refusé -- le mot de passe ne vient jamais en argument, car l'argument apparaît dans le `ps` de tout utilisateur et reste dans l'historique du shell.\nUtilisez la variable {var}, ou laissez phxzipcmd le demander (sans écho), ou envoyez le mot de passe par l'entrée standard : phxzipcmd ... < fichier-du-mot-de-passe",
        "{opcao} refused -- the password never comes as an argument, because the argument shows up in `ps` for every user and stays in the shell history.\nUse the variable {var}, or let phxzipcmd ask (without echo), or send the password on standard input: phxzipcmd ... < password-file",
        "{opcao} rifiutato -- la password non arriva mai come argomento, perché l'argomento compare nel `ps` di qualsiasi utente e resta nella cronologia della shell.\nUsa la variabile {var}, o lascia che phxzipcmd la chieda (senza eco), o manda la password dall'input standard: phxzipcmd ... < file-della-password",
        "{opcao} abgelehnt -- das Passwort kommt nie als Argument, weil das Argument in `ps` für jeden Benutzer sichtbar ist und im Shell-Verlauf bleibt.\nVerwenden Sie die Variable {var}, lassen Sie phxzipcmd fragen (ohne Echo) oder senden Sie das Passwort über die Standardeingabe: phxzipcmd ... < passwort-datei",
        "{opcao} rechazado -- la contraseña nunca viene por argumento, porque el argumento aparece en el `ps` de cualquier usuario y queda en el historial del shell.\nUse la variable {var}, o deje que phxzipcmd la pregunte (sin eco), o mande la contraseña por la entrada estándar: phxzipcmd ... < archivo-de-la-contraseña"),
    texto!("zipcmd.senha_ler_falhou",
        "nao consegui ler a senha da entrada padrao: {erro}",
        "impossible de lire le mot de passe sur l'entrée standard : {erro}",
        "could not read the password from standard input: {erro}",
        "non sono riuscito a leggere la password dall'input standard: {erro}",
        "konnte das Passwort nicht von der Standardeingabe lesen: {erro}",
        "no pude leer la contraseña de la entrada estándar: {erro}"),
    texto!("zipcmd.senha_longa",
        "a senha passa de {teto} bytes sem quebra de linha",
        "le mot de passe dépasse {teto} octets sans saut de ligne",
        "the password exceeds {teto} bytes without a line break",
        "la password supera {teto} byte senza andare a capo",
        "das Passwort überschreitet {teto} Bytes ohne Zeilenumbruch",
        "la contraseña pasa de {teto} bytes sin salto de línea"),
    texto!("zipcmd.senha_ausente",
        "a entrada padrao terminou sem senha; use {var} ou mande a senha pela entrada",
        "l'entrée standard s'est terminée sans mot de passe ; utilisez {var} ou envoyez le mot de passe par l'entrée",
        "standard input ended without a password; use {var} or send the password on the input",
        "l'input standard è finito senza password; usa {var} o manda la password dall'input",
        "die Standardeingabe endete ohne Passwort; verwenden Sie {var} oder senden Sie das Passwort über die Eingabe",
        "la entrada estándar terminó sin contraseña; use {var} o mande la contraseña por la entrada"),
    texto!("zipcmd.senha_nao_utf8",
        "a senha nao e UTF-8",
        "le mot de passe n'est pas en UTF-8",
        "the password is not UTF-8",
        "la password non è UTF-8",
        "das Passwort ist kein UTF-8",
        "la contraseña no es UTF-8"),
    texto!("zipcmd.senha_vazia",
        "senha vazia",
        "mot de passe vide",
        "empty password",
        "password vuota",
        "leeres Passwort",
        "contraseña vacía"),
    texto!("zipcmd.sem_eco",
        "nao consegui desligar o eco do terminal (/bin/stty), e a senha nao se digita a vista; use {var} ou mande a senha pela entrada padrao (phxzipcmd ... < arquivo)",
        "impossible de couper l'écho du terminal (/bin/stty), et le mot de passe ne se tape pas à la vue ; utilisez {var} ou envoyez le mot de passe par l'entrée standard (phxzipcmd ... < fichier)",
        "could not turn off terminal echo (/bin/stty), and the password is not typed in plain sight; use {var} or send the password on standard input (phxzipcmd ... < file)",
        "non sono riuscito a spegnere l'eco del terminale (/bin/stty), e la password non si digita in chiaro; usa {var} o manda la password dall'input standard (phxzipcmd ... < file)",
        "konnte das Terminal-Echo nicht abschalten (/bin/stty), und das Passwort wird nicht sichtbar getippt; verwenden Sie {var} oder senden Sie das Passwort über die Standardeingabe (phxzipcmd ... < datei)",
        "no pude apagar el eco del terminal (/bin/stty), y la contraseña no se teclea a la vista; use {var} o mande la contraseña por la entrada estándar (phxzipcmd ... < archivo)"),
    texto!("zipcmd.var_nao_utf8",
        "{var} nao e UTF-8",
        "{var} n'est pas en UTF-8",
        "{var} is not UTF-8",
        "{var} non è UTF-8",
        "{var} ist kein UTF-8",
        "{var} no es UTF-8"),
    texto!("zipcmd.var_vazia",
        "{var} esta definida e vazia",
        "{var} est définie et vide",
        "{var} is set and empty",
        "{var} è definita e vuota",
        "{var} ist gesetzt und leer",
        "{var} está definida y vacía"),
    texto!("zipcmd.pergunta_senha",
        "senha: ",
        "mot de passe : ",
        "password: ",
        "password: ",
        "Passwort: ",
        "contraseña: "),
    texto!("zipcmd.pergunta_de_novo",
        "a mesma senha, de novo: ",
        "le même mot de passe, à nouveau : ",
        "the same password, again: ",
        "la stessa password, di nuovo: ",
        "dasselbe Passwort noch einmal: ",
        "la misma contraseña, de nuevo: "),
    texto!("zipcmd.senhas_diferentes",
        "as duas senhas digitadas nao conferem",
        "les deux mots de passe saisis ne correspondent pas",
        "the two passwords typed do not match",
        "le due password digitate non coincidono",
        "die beiden eingegebenen Passwörter stimmen nicht überein",
        "las dos contraseñas tecleadas no coinciden"),

    // ------------------------------------------------------------ a linha de comando
    texto!("zipcmd.falta_comando",
        "falta o comando",
        "il manque la commande",
        "missing the command",
        "manca il comando",
        "der Befehl fehlt",
        "falta el comando"),
    texto!("zipcmd.comando_desconhecido",
        "comando desconhecido: {comando}",
        "commande inconnue : {comando}",
        "unknown command: {comando}",
        "comando sconosciuto: {comando}",
        "unbekannter Befehl: {comando}",
        "comando desconocido: {comando}"),
    texto!("zipcmd.opcao_nao_vale",
        "{opcao} nao vale para este comando",
        "{opcao} ne vaut pas pour cette commande",
        "{opcao} does not apply to this command",
        "{opcao} non vale per questo comando",
        "{opcao} gilt nicht für diesen Befehl",
        "{opcao} no vale para este comando"),
    texto!("zipcmd.destino_pede_pasta",
        "--destino pede uma pasta",
        "--destino demande un dossier",
        "--destino needs a folder",
        "--destino richiede una cartella",
        "--destino verlangt einen Ordner",
        "--destino pide una carpeta"),
    texto!("zipcmd.ciclos_pede_numero",
        "--ciclos pede um numero",
        "--ciclos demande un nombre",
        "--ciclos needs a number",
        "--ciclos richiede un numero",
        "--ciclos verlangt eine Zahl",
        "--ciclos pide un número"),
    texto!("zipcmd.ciclos_fora",
        "--ciclos vai de 0 a {maximo}, veio {veio}",
        "--ciclos va de 0 à {maximo}, reçu {veio}",
        "--ciclos goes from 0 to {maximo}, got {veio}",
        "--ciclos va da 0 a {maximo}, arrivato {veio}",
        "--ciclos geht von 0 bis {maximo}, erhalten {veio}",
        "--ciclos va de 0 a {maximo}, llegó {veio}"),
    texto!("zipcmd.opcao_desconhecida",
        "opcao desconhecida: {opcao}",
        "option inconnue : {opcao}",
        "unknown option: {opcao}",
        "opzione sconosciuta: {opcao}",
        "unbekannte Option: {opcao}",
        "opción desconocida: {opcao}"),
    texto!("zipcmd.so_com_cifrar",
        "--nomes-claros e --ciclos so valem com --cifrar",
        "--nomes-claros et --ciclos ne valent qu'avec --cifrar",
        "--nomes-claros and --ciclos only apply with --cifrar",
        "--nomes-claros e --ciclos valgono solo con --cifrar",
        "--nomes-claros und --ciclos gelten nur mit --cifrar",
        "--nomes-claros y --ciclos solo valen con --cifrar"),
    texto!("zipcmd.falta_arquivo",
        "falta o ARQUIVO.7z",
        "il manque l'ARCHIVE.7z",
        "missing the ARCHIVE.7z",
        "manca l'ARCHIVIO.7z",
        "das ARCHIV.7z fehlt",
        "falta el ARCHIVO.7z"),
    texto!("zipcmd.falta_caminho",
        "compactar pede ao menos um CAMINHO",
        "compactar demande au moins un CHEMIN",
        "compactar needs at least one PATH",
        "compactar richiede almeno un PERCORSO",
        "compactar verlangt mindestens einen PFAD",
        "compactar pide al menos una RUTA"),
    texto!("zipcmd.arquivo_so_um",
        "este comando recebe um ARQUIVO.7z so",
        "cette commande reçoit une seule ARCHIVE.7z",
        "this command takes a single ARCHIVE.7z",
        "questo comando riceve un solo ARCHIVIO.7z",
        "dieser Befehl nimmt nur ein ARCHIV.7z",
        "este comando recibe un solo ARCHIVO.7z"),

    // ------------------------------------------------------------ ler e listar
    texto!("zipcmd.passa_do_teto",
        "{nome}: passa do teto de {teto} bytes; para arquivo que voce mesmo gravou, --confiavel",
        "{nome} : dépasse le plafond de {teto} octets ; pour une archive que vous avez écrite vous-même, --confiavel",
        "{nome}: exceeds the cap of {teto} bytes; for an archive you wrote yourself, --confiavel",
        "{nome}: supera il tetto di {teto} byte; per un archivio scritto da te, --confiavel",
        "{nome}: überschreitet die Grenze von {teto} Bytes; für ein selbst geschriebenes Archiv: --confiavel",
        "{nome}: pasa del tope de {teto} bytes; para un archivo que usted mismo grabó, --confiavel"),
    texto!("zipcmd.col_tamanho", "tamanho", "taille", "size", "dimensione", "Größe", "tamaño"),
    texto!("zipcmd.col_modificado", "modificado (UTC)", "modifié (UTC)", "modified (UTC)", "modificato (UTC)", "geändert (UTC)", "modificado (UTC)"),
    texto!("zipcmd.col_tipo", "tipo", "type", "type", "tipo", "Typ", "tipo"),
    texto!("zipcmd.col_nome", "nome", "nom", "name", "nome", "Name", "nombre"),
    texto!("zipcmd.total_listado",
        "{entradas} entrada(s), {bytes} bytes",
        "{entradas} entrée(s), {bytes} octets",
        "{entradas} entry(ies), {bytes} bytes",
        "{entradas} voce/i, {bytes} byte",
        "{entradas} Eintrag/Einträge, {bytes} Bytes",
        "{entradas} entrada(s), {bytes} bytes"),
    texto!("zipcmd.sufixo_cabecalho_cifrado",
        ", cabecalho cifrado",
        ", en-tête chiffré",
        ", encrypted header",
        ", intestazione cifrata",
        ", verschlüsselter Header",
        ", cabecera cifrada"),
    texto!("zipcmd.testar_ok",
        "ok: {n} entrada(s) conferida(s)",
        "ok : {n} entrée(s) vérifiée(s)",
        "ok: {n} entry(ies) checked",
        "ok: {n} voce/i verificata/e",
        "ok: {n} Eintrag/Einträge geprüft",
        "ok: {n} entrada(s) comprobada(s)"),

    // ------------------------------------------------------------ extrair
    texto!("zipcmd.destino_falhou",
        "nao consegui criar o destino {destino}: {erro}",
        "impossible de créer la destination {destino} : {erro}",
        "could not create the destination {destino}: {erro}",
        "non sono riuscito a creare la destinazione {destino}: {erro}",
        "konnte das Ziel {destino} nicht anlegen: {erro}",
        "no pude crear el destino {destino}: {erro}"),
    texto!("zipcmd.aviso_link_gravado_comum",
        "aviso: {nome} veio marcada como link simbolico; gravada como arquivo comum (o PhxZipCmd nao cria link)",
        "avertissement : {nome} est marquée comme lien symbolique ; écrite comme fichier ordinaire (PhxZipCmd ne crée pas de lien)",
        "warning: {nome} came marked as a symbolic link; written as a regular file (PhxZipCmd does not create links)",
        "avviso: {nome} è marcata come link simbolico; scritta come file normale (PhxZipCmd non crea link)",
        "Warnung: {nome} ist als symbolischer Link markiert; als normale Datei geschrieben (PhxZipCmd legt keine Links an)",
        "aviso: {nome} vino marcada como enlace simbólico; grabada como archivo común (PhxZipCmd no crea enlaces)"),
    texto!("zipcmd.extracao_interrompida",
        "{erro}; extracao interrompida com {gravadas} entrada(s) ja gravada(s) em {destino}",
        "{erro} ; extraction interrompue avec {gravadas} entrée(s) déjà écrite(s) dans {destino}",
        "{erro}; extraction stopped with {gravadas} entry(ies) already written in {destino}",
        "{erro}; estrazione interrotta con {gravadas} voce/i già scritta/e in {destino}",
        "{erro}; Entpacken abgebrochen, {gravadas} Eintrag/Einträge bereits in {destino} geschrieben",
        "{erro}; extracción interrumpida con {gravadas} entrada(s) ya grabada(s) en {destino}"),
    texto!("zipcmd.extraidas",
        "{n} entrada(s) extraida(s) em {destino}",
        "{n} entrée(s) extraite(s) dans {destino}",
        "{n} entry(ies) extracted to {destino}",
        "{n} voce/i estratta/e in {destino}",
        "{n} Eintrag/Einträge nach {destino} entpackt",
        "{n} entrada(s) extraída(s) en {destino}"),

    // ------------------------------------------------------------ compactar
    texto!("zipcmd.aviso_link_pulado",
        "aviso: {caminho} e link, pulado (o PhxZipCmd nao segue link)",
        "avertissement : {caminho} est un lien, ignoré (PhxZipCmd ne suit pas les liens)",
        "warning: {caminho} is a link, skipped (PhxZipCmd does not follow links)",
        "avviso: {caminho} è un link, saltato (PhxZipCmd non segue i link)",
        "Warnung: {caminho} ist ein Link, übersprungen (PhxZipCmd folgt keinen Links)",
        "aviso: {caminho} es enlace, saltado (PhxZipCmd no sigue enlaces)"),
    texto!("zipcmd.aviso_especial_pulado",
        "aviso: {caminho} nao e arquivo comum nem pasta, pulado",
        "avertissement : {caminho} n'est ni un fichier ordinaire ni un dossier, ignoré",
        "warning: {caminho} is neither a regular file nor a folder, skipped",
        "avviso: {caminho} non è né un file normale né una cartella, saltato",
        "Warnung: {caminho} ist weder normale Datei noch Ordner, übersprungen",
        "aviso: {caminho} no es archivo común ni carpeta, saltado"),
    texto!("zipcmd.nome_nao_utf8_na_pasta",
        "{caminho}: nome que nao e UTF-8 dentro da pasta",
        "{caminho} : nom qui n'est pas en UTF-8 dans le dossier",
        "{caminho}: a name that is not UTF-8 inside the folder",
        "{caminho}: nome non UTF-8 dentro la cartella",
        "{caminho}: Name im Ordner ist kein UTF-8",
        "{caminho}: nombre que no es UTF-8 dentro de la carpeta"),
    texto!("zipcmd.trocado_durante",
        "{nome}: trocado durante a compactacao (o que se abriu nao e o arquivo que se olhou -- um link posto no lugar?); nada foi gravado",
        "{nome} : remplacé pendant la compression (ce qui a été ouvert n'est pas le fichier examiné -- un lien mis à sa place ?) ; rien n'a été écrit",
        "{nome}: swapped during compression (what was opened is not the file that was examined -- a link put in its place?); nothing was written",
        "{nome}: scambiato durante la compressione (ciò che si è aperto non è il file esaminato -- un link messo al suo posto?); non è stato scritto nulla",
        "{nome}: während des Komprimierens ausgetauscht (das Geöffnete ist nicht die geprüfte Datei -- ein Link an ihrer Stelle?); nichts wurde geschrieben",
        "{nome}: cambiado durante la compresión (lo que se abrió no es el archivo que se miró -- ¿un enlace puesto en su lugar?); no se grabó nada"),
    texto!("zipcmd.caminho_sem_nome",
        "{caminho}: caminho sem nome para guardar",
        "{caminho} : chemin sans nom à conserver",
        "{caminho}: path without a name to store",
        "{caminho}: percorso senza nome da salvare",
        "{caminho}: Pfad ohne speicherbaren Namen",
        "{caminho}: ruta sin nombre para guardar"),
    texto!("zipcmd.nome_nao_utf8",
        "{caminho}: nome que nao e UTF-8",
        "{caminho} : nom qui n'est pas en UTF-8",
        "{caminho}: a name that is not UTF-8",
        "{caminho}: nome non UTF-8",
        "{caminho}: Name ist kein UTF-8",
        "{caminho}: nombre que no es UTF-8"),
    texto!("zipcmd.ja_existe",
        "{arquivo} ja existe; use --sobrescrever",
        "{arquivo} existe déjà ; utilisez --sobrescrever",
        "{arquivo} already exists; use --sobrescrever",
        "{arquivo} esiste già; usa --sobrescrever",
        "{arquivo} existiert bereits; verwenden Sie --sobrescrever",
        "{arquivo} ya existe; use --sobrescrever"),
    texto!("zipcmd.nada_para_compactar",
        "nada para compactar: so havia link ou arquivo especial",
        "rien à compresser : il n'y avait que des liens ou des fichiers spéciaux",
        "nothing to compress: there were only links or special files",
        "niente da comprimere: c'erano solo link o file speciali",
        "nichts zu komprimieren: es gab nur Links oder Spezialdateien",
        "nada para comprimir: solo había enlaces o archivos especiales"),
    texto!("zipcmd.compactado",
        "{n} entrada(s) em {arquivo}, {bytes} bytes",
        "{n} entrée(s) dans {arquivo}, {bytes} octets",
        "{n} entry(ies) in {arquivo}, {bytes} bytes",
        "{n} voce/i in {arquivo}, {bytes} byte",
        "{n} Eintrag/Einträge in {arquivo}, {bytes} Bytes",
        "{n} entrada(s) en {arquivo}, {bytes} bytes"),
    texto!("zipcmd.sufixo_cifrado",
        ", cifrado",
        ", chiffré",
        ", encrypted",
        ", cifrato",
        ", verschlüsselt",
        ", cifrado"),
];
