use async_trait::async_trait;
use phx_sql_introspection_api::*;
use phx_sql_model::ObjectKind;
use phx_sql_parser_api::SqlDialect;
use sqlx::{sqlite::{SqliteConnectOptions,SqlitePoolOptions}, Row};
use std::{collections::{BTreeMap,HashMap}, time::Duration};

pub struct SqliteIntrospector;
fn quote_ident(name:&str)->String{format!("\"{}\"",name.replace('"',"\"\""))}
fn obj(kind:ObjectKind,schema:Option<String>,name:String,target:Option<String>,definition:Option<String>)->CatalogObject{CatalogObject{kind,schema,name,target,definition,metadata:BTreeMap::new()}}
fn generated_expr(sql:&str,col:&str)->Option<String>{let lower=sql.to_ascii_lowercase();let needle=col.to_ascii_lowercase();let p=lower.find(&needle)?;let tail=&sql[p+needle.len()..];let lt=tail.to_ascii_lowercase();let a=lt.find(" as")?;let open=tail[a..].find('(')?+a;let mut d=0usize;let mut quote=None;for(i,ch)in tail[open..].char_indices(){if let Some(q)=quote{if ch==q{quote=None}continue}if ch=='\''||ch=='\"'{quote=Some(ch);continue}if ch=='(' {d+=1}else if ch==')'{d=d.saturating_sub(1);if d==0{return Some(tail[open+1..open+i].trim().to_string())}}}None}
fn parse_checks(sql:&str)->Vec<CatalogCheckConstraint>{let mut out=vec![];let lower=sql.to_ascii_lowercase();let mut at=0usize;while let Some(rel)=lower[at..].find("check"){let p=at+rel+5;let rest=&sql[p..];let Some(o)=rest.find('(')else{break};let start=p+o;let mut d=0usize;let mut quote=None;let mut end=None;for(i,ch)in sql[start..].char_indices(){if let Some(q)=quote{if ch==q{quote=None}continue}if ch=='\''||ch=='\"'{quote=Some(ch);continue}if ch=='(' {d+=1}else if ch==')'{d=d.saturating_sub(1);if d==0{end=Some(start+i);break}}}if let Some(e)=end{out.push(CatalogCheckConstraint{name:None,expression:sql[start+1..e].trim().into(),column:None});at=e+1}else{break}}out}

#[async_trait]
impl DatabaseIntrospector for SqliteIntrospector{
 fn dialect(&self)->SqlDialect{SqlDialect::Sqlite}
 async fn introspect(&self,spec:&ConnectionSpec,options:&IntrospectionOptions)->Result<CatalogSnapshot,IntrospectionError>{
  if spec.dialect!=SqlDialect::Sqlite{return Err(IntrospectionError::UnsupportedDialect(spec.dialect.as_str().into()))}
  let raw=spec.path.as_deref().filter(|s|!s.is_empty()).unwrap_or(&spec.database);let connect=SqliteConnectOptions::new().filename(raw).read_only(true);let pool=SqlitePoolOptions::new().max_connections(1).acquire_timeout(Duration::from_secs(10)).connect_with(connect).await.map_err(|e|IntrospectionError::Connection(e.to_string()))?;
  let schema_rows=sqlx::query("SELECT name,type,sql FROM sqlite_schema WHERE name NOT LIKE 'sqlite_%' AND type IN ('table','view','index','trigger') ORDER BY type,name").fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;
  let mut defs:HashMap<(String,String),Option<String>>=HashMap::new();for r in &schema_rows{let n:String=r.try_get("name").unwrap_or_default();let t:String=r.try_get("type").unwrap_or_default();defs.insert((t,n),r.try_get("sql").ok());}let table_names=schema_rows.iter().filter_map(|r|{let t:String=r.try_get("type").ok()?;if t!="table"{return None}r.try_get::<String,_>("name").ok()}).collect::<Vec<_>>();if table_names.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(table_names.len()))}
  let mut tables=Vec::new();for name in &table_names{let def=defs.get(&("table".into(),name.clone())).cloned().flatten();let q=format!("PRAGMA table_xinfo({})",quote_ident(name));let rows=sqlx::query(&q).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;let mut columns=vec![];let mut pk_ord=vec![];for r in rows{let cname:String=r.try_get("name").unwrap_or_default();let pk=r.try_get::<i64,_>("pk").unwrap_or(0);if pk>0{pk_ord.push((pk,cname.clone()))}let hidden=r.try_get::<i64,_>("hidden").unwrap_or(0);let gen_kind=match hidden{2=>Some("virtual".into()),3=>Some("stored".into()),_=>None};let expr=if gen_kind.is_some(){def.as_deref().and_then(|s|generated_expr(s,&cname))}else{None};columns.push(CatalogColumn{name:cname,data_type:r.try_get("type").unwrap_or_default(),nullable:r.try_get::<i64,_>("notnull").unwrap_or(0)==0,default_expr:r.try_get("dflt_value").ok(),primary_key:pk>0,unique:false,ordinal:r.try_get::<i64,_>("cid").unwrap_or(0).max(0)as usize+1,generated_expression:expr,generated_kind:gen_kind});}pk_ord.sort_by_key(|x|x.0);let primary_key=pk_ord.into_iter().map(|x|x.1).collect::<Vec<_>>();let fq=format!("PRAGMA foreign_key_list({})",quote_ident(name));let frows=sqlx::query(&fq).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;#[derive(Default)]struct F{to:String,a:Vec<(i64,String)>,b:Vec<(i64,String)>,del:Option<String>}let mut gs:HashMap<i64,F>=HashMap::new();for r in frows{let id=r.try_get::<i64,_>("id").unwrap_or(0);let seq=r.try_get::<i64,_>("seq").unwrap_or(0);let g=gs.entry(id).or_default();g.to=r.try_get("table").unwrap_or_default();g.a.push((seq,r.try_get("from").unwrap_or_default()));g.b.push((seq,r.try_get("to").unwrap_or_default()));g.del=r.try_get("on_delete").ok();}let mut fks=vec![];for(id,mut g)in gs{g.a.sort_by_key(|x|x.0);g.b.sort_by_key(|x|x.0);fks.push(CatalogForeignKey{constraint_name:Some(format!("fk_{name}_{id}")),from_schema:"main".into(),from_table:name.clone(),from_columns:g.a.into_iter().map(|x|x.1).collect(),to_schema:"main".into(),to_table:g.to,to_columns:g.b.into_iter().map(|x|x.1).collect(),on_delete:g.del});}if options.include_indexes{let iq=format!("PRAGMA index_list({})",quote_ident(name));for ir in sqlx::query(&iq).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?{if ir.try_get::<i64,_>("unique").unwrap_or(0)!=1{continue}let iname:String=ir.try_get("name").unwrap_or_default();let ii=format!("PRAGMA index_info({})",quote_ident(&iname));let rr=sqlx::query(&ii).fetch_all(&pool).await.map_err(|e|IntrospectionError::Catalog(e.to_string()))?;if rr.len()==1{let cn:String=rr[0].try_get("name").unwrap_or_default();if let Some(c)=columns.iter_mut().find(|c|c.name.eq_ignore_ascii_case(&cn)){c.unique=true}}}}
   tables.push(CatalogTable{schema:"main".into(),name:name.clone(),columns,primary_key,foreign_keys:fks,check_constraints:def.as_deref().map(parse_checks).unwrap_or_default(),partitioning:None,statistics:None,definition:def});}
  let mut objects=vec![obj(ObjectKind::Schema,None,"main".into(),None,None)];for r in schema_rows{let typ:String=r.try_get("type").unwrap_or_default();let name:String=r.try_get("name").unwrap_or_default();let def:Option<String>=r.try_get("sql").ok();match typ.as_str(){"view" if options.include_views=>objects.push(obj(ObjectKind::View,Some("main".into()),name,None,def)),"index" if options.include_indexes=>objects.push(obj(ObjectKind::Index,Some("main".into()),name,None,def)),"trigger" if options.include_triggers=>objects.push(obj(ObjectKind::Trigger,Some("main".into()),name,None,def)),_=>{}}}
  if tables.len()+objects.len()>options.max_objects{return Err(IntrospectionError::ObjectLimit(tables.len()+objects.len()))}Ok(CatalogSnapshot{dialect:SqlDialect::Sqlite,source_name:spec.safe_source_name(),database_name:spec.database.clone(),tables,objects})
 }
}
