[workspace]
resolver = "2"
members = [
    "crates/phxsql-core",
    "crates/phxsql-store",
    "crates/phxsql-cli",
    "crates/phxsql-server",
]

[workspace.package]
version = "0.16.0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/adrianoboller/adrianoboller"

[workspace.dependencies]
phxsql-core = { path = "crates/phxsql-core" }
phxsql-store = { path = "crates/phxsql-store" }
phxsql-server = { path = "crates/phxsql-server" }

[profile.release]
opt-level = 3
lto = "thin"
