const canvas=document.querySelector('#canvas'),diag=document.querySelector('#diag'),status=document.querySelector('#status'),file=document.querySelector('#file');
const modeler=new window.BpmnJS({container:canvas,keyboard:{bindTo:window}});
const blank=`<?xml version="1.0" encoding="UTF-8"?><bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1" targetNamespace="http://phxclaw.local/bpmn"><bpmn:process id="Process_1" isExecutable="true"><bpmn:startEvent id="StartEvent_1"/></bpmn:process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1"><bpmndi:BPMNShape id="StartEvent_1_di" bpmnElement="StartEvent_1"><dc:Bounds x="160" y="100" width="36" height="36"/></bpmndi:BPMNShape></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></bpmn:definitions>`;
async function load(xml){try{const {warnings}=await modeler.importXML(xml);status.textContent='carregado';diag.textContent=warnings?.length?warnings.map(x=>x.message).join('\n'):'Sem erros.';modeler.get('canvas').zoom('fit-viewport');}catch(e){status.textContent='erro';diag.textContent=e.stack||String(e)}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
document.querySelector('#new').onclick=()=>load(blank);document.querySelector('#open').onclick=()=>file.click();file.onchange=async()=>{if(file.files[0])await load(await file.files[0].text())};
document.querySelector('#save').onclick=async()=>{const {xml}=await modeler.saveXML({format:true});download('process.bpmn',xml,'application/xml')};
document.querySelector('#svg').onclick=async()=>{const {svg}=await modeler.saveSVG();download('process.svg',svg,'image/svg+xml')};
document.querySelector('#validate').onclick=async()=>{const {xml}=await modeler.saveXML({format:true});if(window.phxclawBpmBridge?.validate){const r=await window.phxclawBpmBridge.validate(xml);diag.textContent=JSON.stringify(r,null,2)}else{diag.textContent='Validação estrutural local OK. Bridge PhxClaw não conectado.'}};
load(blank);
