#!/usr/bin/env python3
from pathlib import Path
import json,re,sys,hashlib
here=Path(__file__).resolve(); base=here.parents[1]; over=base/'overlay' if (base/'overlay').exists() else base
checks=[]
def c(n,o): checks.append({'name':n,'pass':bool(o)})
inv=json.loads((over/'config/historical-table-inventory.v059.json').read_text()); reg=json.loads((over/'config/historical-backfill-registry.v059.json').read_text()); sql=(over/'migrations/0059_historical_backfill.sql').read_text(); py=(over/'tools/backfill_v059.py').read_text(); rs=(over/'crates/phxclaw-historical-backfill/src/lib.rs').read_text(); caps=json.loads((over/'config/capabilities-v059.json').read_text())['capabilities']
its={x['source_table'] for x in inv['tables']}; rts={x['source_table'] for x in reg['sources']}
c('inventory_95',inv['table_count']==95 and len(inv['tables'])==95)
c('registry_95',reg['registry_count']==95 and len(reg['sources'])==95)
c('registry_exact_inventory',its==rts)
c('registry_unique',len(rts)==95)
c('inventory_all_tenant_scoped',all('tenant_uuid' in x['columns'] for x in inv['tables']))
c('capabilities_64',len(caps)==64)
c('priority_direct_first',all(x['priority']==10 for x in reg['sources'] if x['scope_policy']=='direct_project'))
c('scope_policies',all(x['scope_policy'] in {'direct_project','reference_required','portfolio_scope','tenant_scope'} for x in reg['sources']))
c('control_runs','phx_historical_backfill_runs' in sql)
c('checkpoints_append_only','phx_historical_backfill_checkpoints' in sql and 'checkpoints_immutable' in sql)
c('identity_map','phx_historical_backfill_identity_map' in sql)
c('scope_map','phx_historical_backfill_scope_map' in sql)
c('orphans','phx_historical_backfill_orphans' in sql)
c('coverage','phx_historical_backfill_coverage' in sql and 'coverage_ratio' in sql)
c('events_append_only','phx_historical_backfill_events_immutable' in sql)
c('rls_force_loop','FORCE ROW LEVEL SECURITY' in sql and "phx.tenant_uuid" in sql)
c('progress_view','phx_historical_backfill_progress_v' in sql)
c('trace_target',all(x in py for x in ['phx_project_trace_nodes','phx_project_trace_bindings','phx_project_source_documents']))
c('resume_support','--resume-run' in py and 'registry drift' in py)
c('batch_support','--batch-size' in py and 'checkpoint_seq' in py)
c('keyset_resume','pk_keyset' in py and "cursor.get('last_pk')" in py and 'ORDER BY ctid' in py)
c('raw_row_provenance','raw_row_hash=sha256_obj(row)' in py)
c('orphan_table_retry','--only-table' in py)
c('tenant_required',"--tenant is required for live execution" in py)
c('db_credentials_env_only','PHXCLAW_DATABASE_URL' in py and '--password' not in py)
c('safe_identifiers','SAFE_IDENT' in py and 'unsafe registry table identifier' in py)
c('tenant_advisory_lock','pg_try_advisory_lock' in py and 'another v0.59 backfill' in py)
c('missing_table_zero_coverage',"0,0,0,0,0,0,'missing_table'" in py)
c('uuid7_python','def uuid7()' in py and '0x7<<76' in py)
c('row_source_capture',"'postgresql-row'" in py and 'postgresql://' in py)
c('raw_row_not_metadata',"'source_key_sha256':key" in py and 'metadata=clean_json(row)' not in py)
c('secret_scrub',all(k in py for k in ['access_token','refresh_token','private_key']))
c('project_resolution',all(k in py for k in ['direct_project','reference_required','portfolio_scope','tenant_scope']))
c('parent_resolution','parent_ref_columns' in py and 'resolve_bound_node' in py)
c('cross_links','link_ref_columns' in py and 'phx_project_trace_links' in py)
c('rust_contract','BackfillCheckpoint' in rs and 'CoverageSnapshot' in rs and 'OrphanRecord' in rs)
c('ui',(over/'ui/historical-backfill.html').exists())
fail=[x for x in checks if not x['pass']]; out={'suite':'v0.59 static','pass':len(checks)-len(fail),'fail':len(fail),'checks':checks};print(json.dumps(out,indent=2));sys.exit(1 if fail else 0)
