#!/usr/bin/env python3
from pathlib import Path
import json, sys, tomllib
HERE=Path(__file__).resolve(); PKG=HERE.parents[1]; ROOT=PKG/'overlay' if (PKG/'overlay/capabilities/V033_CAPABILITIES_DELTA.json').is_file() else PKG; REPORT=PKG/'reports' if (PKG/'overlay').exists() else ROOT/'reports'; checks=[]
def ck(n,o,d=''): checks.append({'name':n,'pass':bool(o),'detail':d}); print(('PASS' if o else 'FAIL'),n,d)
cap=json.loads((ROOT/'capabilities/V033_CAPABILITIES_DELTA.json').read_text()); ck('cap_delta',cap['delta_count']==30); ck('cap_total',cap['projected_total']==451); ck('cap_unique',len(set(cap['capabilities']))==30)
for c in ['phxclaw-model-arena','phxclaw-model-drift']:
 p=ROOT/f'crates/{c}/Cargo.toml'; ck('crate_'+c,p.is_file())
 if p.is_file():
  try: data=tomllib.loads(p.read_text()); ck('toml_'+c,True); ck('version_'+c,data['package']['version']=='0.33.0'); ck('unsafe_forbid_'+c,'unsafe_code = "forbid"' in p.read_text())
  except Exception as e: ck('toml_'+c,False,str(e))
arena=(ROOT/'crates/phxclaw-model-arena/src/lib.rs').read_text()
for n,s in [('candidate_key','struct CandidateKey'),('modes','enum ArenaMode'),('state_event','struct ArenaStateEvent'),('state_transition','transition_state'),('invalid_transition','InvalidStateTransition'),('signed_doc','SignedArenaDocument'),('verified_doc','VerifiedArenaDocument'),('ed25519','VerifyingKey'),('trusted_signer','UntrustedSigner'),('canonical_spec','canonical_spec_bytes'),('eligibility_guard','CandidateIneligible'),('promoted_guard','MissingPromotedProfile'),('promoted_candidate_filter','has_promoted_candidate'),('eligible_filter','eligible.contains'),('deterministic_assignment','assignment_hash'),('shadow','ArenaMode::Shadow'),('canary','ArenaMode::Canary'),('paired','ArenaMode::Paired'),('pair_observation','ArenaPairObservation'),('window','ArenaWindow'),('verdict','ArenaVerdict'),('fixture_block','FixtureNotPromotable'),('consecutive_wins','required_consecutive_wins'),('recommendation','PromotionRecommendation'),('v032_gate','requires_v032_promotion_gate:true'),('profile_match','promoted_profile_matches_arena'),('assign_verified','doc:&VerifiedArenaDocument'),('assign_promoted_profiles','promoted_profiles:&[PromotedProfile]')]: ck('arena_'+n,s in arena)
ck('arena_no_raw_prompt','raw_prompt' not in arena and 'prompt_content' not in arena); ck('arena_no_raw_output','raw_output' not in arena and 'output_content' not in arena)
drift=(ROOT/'crates/phxclaw-model-drift/src/lib.rs').read_text()
for n,s in [('policy','struct DriftPolicy'),('severity','enum DriftSeverity'),('fallback','FallbackBaseRouter'),('fixture_boundary','FixtureEvidence'),('baseline','profile.profile_sha256'),('promoted_baseline','baseline:&PromotedProfile'),('quality_drop','quality_drop'),('success_drop','success_drop'),('latency','latency_regression_basis_points'),('cost','cost_regression_basis_points'),('safety','safety_violation'),('event_hash','event_sha256')]: ck('drift_'+n,s in drift)
policy=json.loads((ROOT/'config/model-arena-policy.v033.json').read_text()); ck('policy_shadow_default',policy['default_mode']=='shadow'); ck('policy_no_raw_prompts',policy['store_raw_prompts'] is False); ck('policy_no_raw_outputs',policy['store_raw_outputs'] is False); ck('policy_fixture_block',policy['fixture_evidence_can_promote'] is False); ck('policy_v031_authority',policy['base_router_authority']=='v0.31'); ck('policy_v032_authority',policy['profile_promotion_authority']=='v0.32'); ck('policy_never_broadens','arena_never_broadens_base_eligibility' in policy['production_rules'])
sql=(ROOT/'migrations/0033_continuous_model_arena.sql').read_text()
need=['phxclaw_ai_arenas','phxclaw_ai_arena_state_events','phxclaw_ai_arena_challengers','phxclaw_ai_arena_assignments','phxclaw_ai_arena_pair_observations','phxclaw_ai_arena_windows','phxclaw_ai_arena_verdicts','phxclaw_ai_arena_promotion_recommendations','phxclaw_ai_drift_events','FORCE ROW LEVEL SECURITY','phxclaw_ai_arena_no_mutation','REFERENCES phxclaw_ai_performance_profiles','REFERENCES phxclaw_ai_providers','REFERENCES phxclaw_ai_models','UNIQUE(tenant_uuid,arena_uuid,request_uuid)']
for s in need: ck('sql_'+s[:28].replace(' ','_'),s in sql)
ck('sql_tenant_setting',"current_setting(''phxclaw.tenant_uuid'', true), '''')" in sql); ck('sql_evidence_class',"evidence_class IN ('production','fixture')" in sql); ck('sql_immutable_spec',"ARRAY['phxclaw_ai_arenas','phxclaw_ai_arena_state_events','phxclaw_ai_arena_challengers'" in sql); ck('sql_no_raw_prompt','raw_prompt' not in sql and 'prompt_content' not in sql); ck('sql_no_raw_output','raw_output' not in sql and 'output_content' not in sql)
for s in (ROOT/'schemas').glob('*v033.schema.json'):
 try: json.loads(s.read_text()); ck('schema_'+s.name,True)
 except Exception as e: ck('schema_'+s.name,False,str(e))
doc=(ROOT/'docs/CONTINUOUS_MODEL_ARENA_V033.md').read_text(); ck('doc_authority_chain','v0.31 safety/cost/privacy eligibility' in doc and 'v0.32 Promotion Gate' in doc); ck('doc_no_global','No global leaderboard' in doc); ck('doc_fixture','Fixtures prove Arena mechanics only' in doc); ck('doc_never_broadens','never broadens the candidate set' in doc); ck('doc_promoted_required','must also have matching promoted v0.32 profiles' in doc); ck('doc_immutable_spec','immutable after registration' in doc)
ci=(ROOT/'ci/run-v033-native.sh').read_text(); ck('ci_locked','--locked' in ci); ck('ci_clippy','cargo clippy' in ci); ck('ci_psql','0033_continuous_model_arena.sql' in ci)
report={'suite':'PhxClaw v0.33 static verifier','pass':sum(x['pass'] for x in checks),'fail':sum(not x['pass'] for x in checks),'checks':checks}; REPORT.mkdir(parents=True,exist_ok=True); (REPORT/'V033_STATIC_VERIFY_REPORT.json').write_text(json.dumps(report,indent=2)+'\n'); print(json.dumps({'pass':report['pass'],'fail':report['fail']})); sys.exit(1 if report['fail'] else 0)
