import {createEnhancer} from './src/enhancer.js';
import {createAnalysisService} from './src/analysis-service.js';
import {assertUnifiedSqlModel, decorateUnifiedSqlModel} from './src/model/unified-model.js';
import {createLiveDbDialog} from './src/live-db-dialog.js';
import {diffSchemas} from './src/schema-diff.js';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const SVG_NS = 'http://www.w3.org/2000/svg';

const state = {
  model:null, rawSql:'', fileSql:'', view:'mindset', selected:null, migration:null, depth:1,
  labels:true, motion:true, theme:'dark', inspectorTab:'structure', query:'',
  graph:{zoom:1,panX:0,panY:0,nodes:[],edges:[],hover:null,drag:null,raf:0},
  rel:{zoom:1,panX:0,panY:0,layout:null},
  mind:{zoom:1}, hybrid:{zoom:1},
  enhancer:null, analysis:null, liveDialog:null, fileModel:null, liveModel:null, schemaDiff:null,
};

const palette=['#6f80ff','#39cfd9','#a276ff','#4cd49a','#f4b85e','#5da8ff','#e875a5','#60c7a7'];
const kindColors={table:'#5da8ff',view:'#4cd49a',materialized_view:'#53d4a8',sequence:'#67b8ff',function:'#a276ff',trigger:'#f4b85e',index:'#39cfd9',policy:'#e875a5',schema:'#8b98ad',synonym:'#c29cff',event:'#ff9e73',extension:'#80d69d',partition:'#ffcd70'};
const kindLabels={table:'Tabelas',view:'Views',materialized_view:'Mat. views',sequence:'Sequences',function:'Funções',trigger:'Triggers',index:'Índices',policy:'Policies',schema:'Schemas',synonym:'Synonyms',event:'Events',extension:'Extensões',partition:'Partições'};
const kindShort={table:'T',view:'V',materialized_view:'MV',sequence:'SEQ',function:'F',trigger:'TR',index:'I',policy:'P',schema:'S',synonym:'SYN',event:'EV',extension:'EXT',partition:'PT'};

function canonical(s=''){return String(s).replaceAll('"','').trim().toLowerCase()}
function shortName(s=''){return String(s).split('.').pop().replaceAll('"','')}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function truncate(s,n=28){s=String(s??'');return s.length>n?s.slice(0,n-1)+'…':s}
function hash32(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function svgEl(tag,attrs={},text){const n=document.createElementNS(SVG_NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!=null)n.textContent=text;return n}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function fmt(n){return new Intl.NumberFormat('pt-BR').format(n||0)}
function migrationName(v){return state.model?.migrations.find(m=>m.version===v)?.name||`Migration ${String(v).padStart(4,'0')}`}
function tableByName(name){const c=canonical(name);return state.model?.tables.find(t=>canonical(t.name)===c)||null}
function selectedTable(){return state.selected?tableByName(state.selected):null}
function objectCounts(){const m=state.model;const counts={};for(const k of Object.keys(kindLabels))counts[k]=m.objects.filter(o=>o.kind===k).length;counts.table=m.tables.length;return counts}

async function init(){
  wireUi();
  state.analysis=createAnalysisService();
  state.enhancer=createEnhancer({state,$,$$,canonical,shortName,escapeHtml,truncate,hash32,svgEl,fmt,palette,tableByName,selectedTable,bfsLevels,selectTable,applyRelTransform,drawMiniMap,updateZoomLabel,downloadUrl,toast,setEngine});
  state.liveDialog=createLiveDbDialog({
    onStatus:setStatus,toast,
    onModel:(model)=>{
      const m=decorateUnifiedSqlModel(assertUnifiedSqlModel(model),{dialect:model.dialect||'unknown',parser:model.producer||model.parser||'live-introspector'});
      state.liveModel=structuredClone(m);
      state.schemaDiff=state.fileModel?diffSchemas(state.fileModel,state.liveModel):null;
      updateDiffButton();
      activateModel(m,'');
      setStatus(`${m.source||'Banco conectado'} · LIVE · ${fmt(m.stats.tables)} tabelas · ${fmt(m.stats.foreign_keys)} FKs · ${m.producer||m.parser||'catalog'}`);
    }
  });
  state.enhancer.load().then(()=>{ if(state.model && ['relational','obsidian'].includes(state.view)) renderCurrent(); });
  try{
    const [model,sql]=await Promise.all([fetch('assets/baseline.json').then(r=>r.json()),fetch('assets/PhxClaw_PostgreSQL_FULL_INSTALL_v0.60.sql').then(r=>r.text())]);
    state.model=decorateUnifiedSqlModel(assertUnifiedSqlModel(model),{dialect:model.dialect||'postgresql',parser:model.parser||'baseline-contract'});state.fileModel=structuredClone(state.model);state.rawSql=sql;state.fileSql=sql;updateDiffButton();
    const initial=[...model.tables].sort((a,b)=>(b.degree||0)-(a.degree||0))[0]||model.tables[0];
    state.selected=initial?.name||null;
    renderAll();
    setStatus(`Baseline carregado · ${fmt(model.stats.tables)} tabelas · PWA local · worker pronto`);
  }catch(err){console.error(err);setStatus('Falha ao carregar baseline');toast('Não foi possível carregar o baseline. Abra um arquivo .sql.')}
  if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
}

function wireUi(){
  $('#openFileBtn').addEventListener('click',()=>$('#fileInput').click());
  $('#fileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;setStatus(`Detectando dialeto e analisando ${f.name}…`);const text=await f.text();try{const {model,engine,dialect}=await state.analysis.analyze(text,f.name,'auto');const parsed=assertUnifiedSqlModel(model);state.fileModel=structuredClone(parsed);state.fileSql=text;state.schemaDiff=state.liveModel?diffSchemas(state.fileModel,state.liveModel):null;updateDiffButton();activateModel(parsed,text);toast(`${fmt(model.tables.length)} tabelas · ${dialect} · ${engine}`);setStatus(`${f.name} · ${dialect} · ${fmt(model.stats.tables)} tabelas · ${fmt(model.stats.foreign_keys)} FKs · ${engine}`)}catch(err){console.error(err);const d=err?.dialect?` (${err.dialect})`:'';toast(err?.code==='UNSUPPORTED_DIALECT'?`Dialeto detectado${d}; parser ainda não instalado`:'Falha ao analisar SQL');setStatus(`Falha de análise${d}: ${err.message||err}`)}});
  $$('.view-button,.mobile-viewbar button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
  $('#clearMigration').addEventListener('click',()=>{state.migration=null;renderMigrations();renderCurrent()});
  $('#depthRange').addEventListener('input',e=>{state.depth=+e.target.value;$('#depthOutput').textContent=`${state.depth} salto${state.depth>1?'s':''}`;if(state.view==='relational'||state.view==='hybrid')renderCurrent()});
  $('#labelToggle').addEventListener('change',e=>{state.labels=e.target.checked;renderCurrent()});
  $('#motionToggle').addEventListener('change',e=>{state.motion=e.target.checked;if(!state.motion&&state.graph.raf)cancelAnimationFrame(state.graph.raf);renderCurrent()});
  $('#themeBtn').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.theme==='light');renderCurrent();state.enhancer?.refreshObsidian()});
  $('#presentationBtn').addEventListener('click',()=>{document.body.classList.toggle('presentation');setTimeout(renderCurrent,80)});
  $('#inspectorToggle').addEventListener('click',()=>$('#inspector').classList.add('open'));
  $('#closeInspector').addEventListener('click',()=>$('#inspector').classList.remove('open'));
  $$('.inspector-tabs button').forEach(b=>b.addEventListener('click',()=>{state.inspectorTab=b.dataset.tab;$$('.inspector-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderInspector()}));
  $('#searchInput').addEventListener('input',e=>showSearch(e.target.value));
  $('#searchInput').addEventListener('keydown',e=>{if(e.key==='Escape'){hideSearch();e.target.blur()} if(e.key==='Enter'){const first=$('.search-item');if(first)first.click()}});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus();$('#searchInput').select()} if(!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&['1','2','3','4'].includes(e.key)){setView(['mindset','relational','obsidian','hybrid'][+e.key-1])}});
  document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-wrap')&&!e.target.closest('.search-results'))hideSearch()});
  $('#schemaDiffBtn')?.addEventListener('click',openSchemaDiff);
  $('#closeDiffDialog')?.addEventListener('click',()=>$('#diffDialog').close());
  $('#showFileModel')?.addEventListener('click',()=>{if(state.fileModel){activateModel(structuredClone(state.fileModel),state.fileSql);$('#diffDialog').close();toast('Visualizando schema do arquivo')}});
  $('#showLiveModel')?.addEventListener('click',()=>{if(state.liveModel){activateModel(structuredClone(state.liveModel),'');$('#diffDialog').close();toast('Visualizando schema vivo')}});
  $('#zoomIn').addEventListener('click',()=>zoomCurrent(1.15));$('#zoomOut').addEventListener('click',()=>zoomCurrent(1/1.15));$('#fitBtn').addEventListener('click',fitCurrent);$('#focusBtn').addEventListener('click',focusCurrent);$('#exportBtn').addEventListener('click',exportCurrent);
  window.addEventListener('resize',()=>{clearTimeout(window.__phxResize);window.__phxResize=setTimeout(renderCurrent,90)});
  wireObsidianInteractions();wireRelationalInteractions();
}

function activateModel(model,rawSql=''){
  state.enhancer?.destroySigma();state.model=assertUnifiedSqlModel(model);state.rawSql=rawSql;state.selected=model.tables[0]?.name||null;state.migration=null;state.graph.nodes=[];state.rel.userPositioned=false;renderAll();
}
function renderAll(){if(!state.model)return;$('#sourceName').textContent=state.model.source||'SQL';renderMetrics();renderMigrations();renderFilters();renderInspector();renderCurrent()}
function renderMetrics(){const st=state.model.stats;const rows=[['tables','tabelas'],['columns','campos'],['foreign_keys','FKs'],['check_constraints','CHECKs'],['generated_columns','generated'],['partitions','partições'],['functions','funções'],['migrations','migrations']];$('#metrics').innerHTML=rows.map(([k,l])=>`<div class="metric"><b>${fmt(st[k])}</b><span>${l}</span></div>`).join('')}
function renderMigrations(){const list=$('#migrationList');if(!state.model.migrations?.length){list.innerHTML=`<div class="migration-empty">${state.model.source_kind==='live_database'?'Catálogo ao vivo':'Sem migrations detectadas'}</div>`;return}const counts=new Map();for(const t of state.model.tables)counts.set(t.migration,(counts.get(t.migration)||0)+1);list.innerHTML=state.model.migrations.map(m=>`<button class="migration-item ${state.migration===m.version?'active':''}" data-v="${m.version}" type="button"><span class="m-num">${String(m.version).padStart(4,'0')}</span><span class="m-name">${escapeHtml(m.name.replace(/^\d+_/,'').replace(/\.sql$/,''))}</span><span class="m-count">${counts.get(m.version)||0}</span></button>`).join('');$$('.migration-item',list).forEach(b=>b.addEventListener('click',()=>{state.migration=+b.dataset.v;renderMigrations();renderCurrent()}))}
function renderFilters(){const counts=objectCounts();const box=$('#kindFilters');box.innerHTML=Object.keys(kindLabels).map(k=>`<button class="kind-filter active" type="button" data-kind="${k}" style="--c:${kindColors[k]}"><i></i><span>${kindLabels[k]}</span><b>${counts[k]||0}</b></button>`).join('');$('#filterCount').textContent=fmt(Object.values(counts).reduce((a,b)=>a+b,0));$$('.kind-filter',box).forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('active');renderCurrent()}))}
function activeKinds(){return new Set($$('.kind-filter.active').map(x=>x.dataset.kind))}
function setView(view){state.view=view;$$('.view-button,.mobile-viewbar button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view-layer').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$('#breadcrumb').innerHTML=`<span>${escapeHtml(truncate(state.model?.source||'SQL',26))}</span><b>/</b><strong>${view==='relational'?'Relacional':view[0].toUpperCase()+view.slice(1)}</strong>`;renderCurrent()}
function renderCurrent(){if(!state.model)return;const f={mindset:renderMindset,relational:renderRelational,obsidian:renderObsidian,hybrid:renderHybrid}[state.view];f();updateZoomLabel()}
function selectTable(name,{openInspector=false}={}){const t=tableByName(name);if(!t)return;state.selected=t.name;renderInspector();renderCurrent();if(openInspector&&innerWidth<=840)$('#inspector').classList.add('open')}

function renderMindset(){
  const svg=$('#mindsetSvg');svg.innerHTML='';
  const defs=svgEl('defs');defs.innerHTML=`<linearGradient id="rootGrad" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#29376f"/><stop offset="1" stop-color="#17254b"/></linearGradient>`;svg.append(defs);
  const root={x:800,y:500,w:215,h:82},st=state.model.stats;
  const branches=[
    {key:'tables',label:'TABELAS',count:st.tables,color:'#5da8ff',angle:-150},
    {key:'relations',label:'RELAÇÕES',count:st.foreign_keys,color:'#39cfd9',angle:-95},
    {key:'constraints',label:'CONSTRAINTS',count:(st.check_constraints||0)+(st.generated_columns||0),color:'#ffcd70',angle:-35},
    {key:'platform',label:'OBJETOS AVANÇADOS',count:(st.sequences||0)+(st.materialized_views||0)+(st.synonyms||0)+(st.events||0)+(st.extensions||0)+(st.partitions||0),color:'#80d69d',angle:25},
    {key:'migrations',label:'MIGRATIONS',count:st.migrations,color:'#f4b85e',angle:85},
    {key:'runtime',label:'RUNTIME + SEGURANÇA',count:(st.functions||0)+(st.triggers||0)+(st.views||0)+(st.policies||0),color:'#a276ff',angle:145}
  ];
  const layer=svgEl('g',{transform:`translate(0 0) scale(${state.mind.zoom})`});svg.append(layer);const items=[],selected=selectedTable();
  for(const b of branches){const rad=b.angle*Math.PI/180;b.x=800+Math.cos(rad)*395;b.y=500+Math.sin(rad)*310;b.w=160;b.h=48;drawCurve(layer,root.x,root.y,b.x,b.y,b.color,false);drawMindNode(layer,b.x,b.y,b.w,b.h,b.label,`${fmt(b.count)} objetos`,'mind-migration',false,b.color,()=>branchAction(b.key));let subs=[];
    if(b.key==='tables')subs=[...state.model.tables].filter(t=>!state.migration||t.migration===state.migration).sort((a,c)=>(c.degree||0)-(a.degree||0)).slice(0,7).map(t=>({label:shortName(t.name),sub:`${t.columns.length} campos · ${t.degree||0} links`,name:t.name}));
    if(b.key==='relations'&&selected)subs=neighbors(selected.name,1).filter(n=>canonical(n)!==canonical(selected.name)).slice(0,7).map(n=>{const t=tableByName(n);return{label:shortName(n),sub:t?`${t.degree||0} relações`:'relacionada',name:n}});
    if(b.key==='constraints'&&selected)subs=[...(selected.check_constraints||[]).slice(0,4).map((c,i)=>({label:c.name||`CHECK ${i+1}`,sub:truncate(c.expression,24)})),...selected.columns.filter(c=>c.generated_expression).slice(0,3).map(c=>({label:c.name,sub:`${c.generated_kind||'generated'}: ${truncate(c.generated_expression,20)}`}))];
    if(b.key==='platform')subs=state.model.objects.filter(o=>['sequence','materialized_view','synonym','event','extension','partition'].includes(o.kind)&&(!state.migration||o.migration===state.migration)).slice(-7).map(o=>({label:shortName(o.name),sub:o.kind}));
    if(b.key==='migrations'){const ms=state.migration?state.model.migrations.filter(m=>Math.abs(m.version-state.migration)<=3):state.model.migrations.slice(-7);subs=ms.map(m=>({label:String(m.version).padStart(4,'0'),sub:truncate(m.name,22),migration:m.version}))}
    if(b.key==='runtime')subs=state.model.objects.filter(o=>['trigger','view','function','policy'].includes(o.kind)&&(!state.migration||o.migration===state.migration)).slice(-7).map(o=>({label:shortName(o.name),sub:o.kind}));
    const spread=52;subs.forEach((x,i)=>{const along=i-(subs.length-1)/2,outward=108,tx=b.x+Math.cos(rad)*outward+Math.cos(rad+Math.PI/2)*along*spread,ty=b.y+Math.sin(rad)*outward+Math.sin(rad+Math.PI/2)*along*spread;drawCurve(layer,b.x,b.y,tx,ty,b.color,false,.42);drawMindNode(layer,tx,ty,128,34,x.label,x.sub,'mind-table',x.name&&selected&&canonical(x.name)===canonical(selected.name),b.color,()=>{if(x.name)selectTable(x.name,{openInspector:true});if(x.migration){state.migration=x.migration;renderMigrations();renderMindset()}});items.push(x)});
  }
  drawMindNode(layer,root.x,root.y,root.w,root.h,'PhxMindSetSQL',`${fmt(st.tables)} tabelas · ${fmt(st.foreign_keys)} relações`,'mind-root',false,'#7584ff',()=>{});$('#visibleCount').textContent=fmt(branches.length+items.length+1);drawMiniMap();
}
function branchAction(key){if(key==='migrations'){state.migration=state.migration||state.model.migrations.at(-1)?.version;renderMigrations();renderMindset()}else if(key==='tables'){setView('relational')}else if(key==='relations'){setView('obsidian')}else if(key==='constraints'){const t=selectedTable();if(t?.check_constraints?.length)toast(`${t.check_constraints.length} CHECK constraints na tabela em foco`);else toast('Selecione uma tabela com constraints');$('#inspector').classList.add('open')}else setView('hybrid')}
function drawCurve(layer,x1,y1,x2,y2,color,hot=false,opacity=.75){const mx=(x1+x2)/2;const p=svgEl('path',{d:`M ${x1} ${y1} C ${mx} ${y1}, ${mx} ${y2}, ${x2} ${y2}`,class:`mind-link${hot?' hot':''}`,stroke:color,opacity});layer.append(p)}
function drawMindNode(layer,x,y,w,h,title,sub,cls,selected,color,onClick){const g=svgEl('g',{class:`mind-node ${cls}${selected?' selected':''}`,transform:`translate(${x-w/2} ${y-h/2})`,role:'button'});const r=svgEl('rect',{class:'node-bg',x:0,y:0,width:w,height:h,rx:cls==='mind-root'?17:9});r.style.stroke=color;const accent=svgEl('rect',{x:0,y:0,width:3,height:h,rx:2,fill:color,opacity:.9});const tt=svgEl('text',{class:'title',x:cls==='mind-root'?w/2:12,y:cls==='mind-root'?34:15,'text-anchor':cls==='mind-root'?'middle':'start'},title);const ss=svgEl('text',{class:'sub',x:cls==='mind-root'?w/2:12,y:cls==='mind-root'?55:27,'text-anchor':cls==='mind-root'?'middle':'start'},sub);g.append(r,accent,tt,ss);g.addEventListener('click',onClick);layer.append(g)}

function neighbors(name,depth=1){const start=canonical(name),seen=new Set([start]),front=new Set([start]);for(let d=0;d<depth;d++){const next=new Set;for(const fk of state.model.relationships){const a=canonical(fk.from_table),b=canonical(fk.to_table);if(front.has(a)&&!seen.has(b))next.add(b);if(front.has(b)&&!seen.has(a))next.add(a)}for(const x of next)seen.add(x);front.clear();for(const x of next)front.add(x);if(!next.size)break}return [...seen].map(c=>state.model.tables.find(t=>canonical(t.name)===c)?.name||c)}
function bfsLevels(name,depth){const start=canonical(name),levels=new Map([[start,0]]),q=[start];while(q.length){const cur=q.shift(),lv=levels.get(cur);if(lv>=depth)continue;for(const fk of state.model.relationships){let other=null;const a=canonical(fk.from_table),b=canonical(fk.to_table);if(a===cur)other=b;else if(b===cur)other=a;if(other&&!levels.has(other)){levels.set(other,lv+1);q.push(other)}}}return levels}
async function renderRelational(){
  if(state.enhancer?.hasElk()){try{const ok=await state.enhancer.renderRelational();if(ok)return}catch(err){console.warn('ELK fallback',err);setEngine('Canvas / Fallback')}}
  return renderRelationalFallback();
}
function renderRelationalFallback(){
  const root=selectedTable()||state.model.tables[0];if(!root)return;
  const levels=bfsLevels(root.name,state.depth);let names=[...levels.keys()];if(state.migration)names=names.filter(n=>tableByName(n)?.migration===state.migration||n===canonical(root.name));names=names.slice(0,16);
  const stageRect=$('#relationalView').getBoundingClientRect();const W=Math.max(700,stageRect.width),H=Math.max(500,stageRect.height);const byLevel=new Map();for(const n of names){const l=levels.get(n)||0;if(!byLevel.has(l))byLevel.set(l,[]);byLevel.get(l).push(n)}
  const pos=new Map();const maxLevel=Math.max(...byLevel.keys(),0);for(const[l,arr]of byLevel){arr.sort((a,b)=>(tableByName(b)?.degree||0)-(tableByName(a)?.degree||0));const x=W/2+(l===0?0:(l%2?1:-1)*Math.ceil(l/2)*300);const total=(arr.length-1)*Math.min(190,Math.max(112,(H-140)/Math.max(1,arr.length-1)));arr.forEach((n,i)=>pos.set(n,{x:x-119,y:H/2-total/2+i*(arr.length>1?total/(arr.length-1):0)-80}))}
  // move crowded level-2 to outer sides based on incoming direction
  if(maxLevel>=2){const arr=byLevel.get(2)||[];arr.forEach((n,i)=>{const p=pos.get(n);p.x=W/2+(i%2?1:-1)*(560+Math.floor(i/2)*8);p.y=80+(i%Math.ceil(arr.length/2))*150})}
  const nodeLayer=$('#relationalNodes'),edgeSvg=$('#relationalEdges');nodeLayer.innerHTML='';edgeSvg.innerHTML='';edgeSvg.setAttribute('viewBox',`0 0 ${W} ${H}`);
  for(const n of names){const t=tableByName(n),p=pos.get(n);if(!t||!p)continue;const card=document.createElement('div');card.className='table-card'+(canonical(t.name)===canonical(root.name)?' selected':'');card.style.left=`${p.x}px`;card.style.top=`${p.y}px`;const fkCols=new Set(t.foreign_keys.flatMap(f=>f.from_columns.map(canonical)));const rows=t.columns.slice(0,7).map(c=>`<div class="table-row"><span class="key ${c.primary_key?'pk':fkCols.has(canonical(c.name))?'fk':''}">${c.primary_key?'PK':fkCols.has(canonical(c.name))?'FK':''}</span><span class="col-name">${escapeHtml(c.name)}</span><span class="col-type">${escapeHtml(truncate(c.data_type,14))}</span></div>`).join('');card.innerHTML=`<div class="table-head"><strong>${escapeHtml(shortName(t.name))}</strong><span>${escapeHtml(t.name.includes('.')?t.name.split('.')[0]:'public')} · ${t.columns.length} campos · ${t.degree||0} links</span></div><div class="table-columns">${rows}${t.columns.length>7?`<div class="more-row">+ ${t.columns.length-7} campos</div>`:''}</div>`;card.addEventListener('click',()=>selectTable(t.name,{openInspector:true}));nodeLayer.append(card);p.w=238;p.h=41+Math.min(7,t.columns.length)*24+(t.columns.length>7?23:0)}
  const nameSet=new Set(names);for(const fk of state.model.relationships){const a=canonical(fk.from_table),b=canonical(fk.to_table);if(!nameSet.has(a)||!nameSet.has(b)||!pos.has(a)||!pos.has(b))continue;const pa=pos.get(a),pb=pos.get(b);const ax=pa.x+pa.w/2,ay=pa.y+pa.h/2,bx=pb.x+pb.w/2,by=pb.y+pb.h/2;const sx=ax<bx?pa.x+pa.w:pa.x,ex=ax<bx?pb.x:pb.x+pb.w;const c1=sx+(ex-sx)*.48;const path=svgEl('path',{d:`M${sx},${ay} C${c1},${ay} ${ex-(ex-sx)*.48},${by} ${ex},${by}`,class:`fk-line${a===canonical(root.name)||b===canonical(root.name)?' selected':''}`});edgeSvg.append(path);edgeSvg.append(svgEl('circle',{cx:sx,cy:ay,r:2.2,class:'fk-dot'}),svgEl('circle',{cx:ex,cy:by,r:2.2,class:'fk-dot'}));if(state.labels&&Math.abs(ex-sx)>90){edgeSvg.append(svgEl('text',{x:sx+(ex-sx)*.11,y:ay-5,class:'cardinality'},'N'),svgEl('text',{x:ex-(ex-sx)*.11,y:by-5,class:'cardinality'},'1'))}}
  state.rel.layout={pos,names,W,H};applyRelTransform();$('#visibleCount').textContent=fmt(names.length);drawMiniMap();
}
function applyRelTransform(){const w=$('#relationalWorld');w.style.transform=`translate(${state.rel.panX}px,${state.rel.panY}px) scale(${state.rel.zoom})`;updateZoomLabel()}

function buildGraph(){
  const tables=state.model.tables.filter(t=>!state.migration||t.migration===state.migration);const allowed=new Set(tables.map(t=>canonical(t.name)));const centerByMig=new Map();for(const m of state.model.migrations){const a=(m.version/state.model.migrations.length)*Math.PI*2;centerByMig.set(m.version,{x:Math.cos(a)*360,y:Math.sin(a)*270})}
  let nodes=tables.map((t,i)=>{const h=hash32(t.name),c=centerByMig.get(t.migration)||{x:0,y:0};const a=(h%6283)/1000,r=35+((h>>>8)%115);return{id:canonical(t.name),name:t.name,label:shortName(t.name),x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r,size:3.2+Math.min(7,Math.sqrt((t.degree||0)+1)*1.4),degree:t.degree||0,migration:t.migration,color:palette[((t.migration||0)-1)%palette.length]}});
  const nodeMap=new Map(nodes.map(n=>[n.id,n]));const edges=[];for(const fk of state.model.relationships){const a=canonical(fk.from_table),b=canonical(fk.to_table);if(allowed.has(a)&&allowed.has(b)&&a!==b)edges.push({a,b})}
  // deterministic refinement: attraction + weak collision, bounded work
  const adj=new Map(nodes.map(n=>[n.id,[]]));for(const e of edges){adj.get(e.a)?.push(e.b);adj.get(e.b)?.push(e.a)}
  for(let it=0;it<36;it++){
    const step=0.035*(1-it/48);for(const n of nodes){let fx=-n.x*.0009,fy=-n.y*.0009;for(const oid of adj.get(n.id)||[]){const o=nodeMap.get(oid);if(!o)continue;const dx=o.x-n.x,dy=o.y-n.y,d=Math.hypot(dx,dy)||1;const target=92;const f=(d-target)*.0025;fx+=dx/d*f;fy+=dy/d*f}n.x+=fx*step*120;n.y+=fy*step*120}
  }
  state.graph.nodes=nodes;state.graph.edges=edges;state.graph.nodeMap=nodeMap;
}
function renderObsidian(){
  if(state.enhancer?.hasSigma()){try{const ok=state.enhancer.renderObsidian();if(ok){$('#visibleCount').textContent=fmt(state.enhancer.rt.sigmaGraph?.order||0);return}}catch(err){console.warn('Sigma fallback',err);setEngine('Canvas / Fallback')}}
  $('#sigmaContainer').hidden=true;$('#obsidianCanvas').hidden=false;return renderObsidianFallback();
}
function renderObsidianFallback(){if(!state.graph.nodes.length||state.graph._migration!==state.migration||state.graph._source!==state.model.source){buildGraph();state.graph._migration=state.migration;state.graph._source=state.model.source;state.graph.zoom=1;state.graph.panX=0;state.graph.panY=0}drawObsidian();$('#visibleCount').textContent=fmt(state.graph.nodes.length);drawMiniMap()}
function drawObsidian(){const canvas=$('#obsidianCanvas'),rect=canvas.getBoundingClientRect(),dpr=Math.min(2.5,devicePixelRatio||1);if(!rect.width||!rect.height)return;canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const cx=rect.width/2+state.graph.panX,cy=rect.height/2+state.graph.panY,z=state.graph.zoom;const themeLight=document.body.classList.contains('light');ctx.lineCap='round';
  // edges
  for(const e of state.graph.edges){const a=state.graph.nodeMap.get(e.a),b=state.graph.nodeMap.get(e.b);if(!a||!b)continue;const ax=cx+a.x*z,ay=cy+a.y*z,bx=cx+b.x*z,by=cy+b.y*z;const hot=canonical(state.selected)===a.id||canonical(state.selected)===b.id;ctx.strokeStyle=hot?(themeLight?'rgba(90,104,220,.48)':'rgba(121,137,255,.58)'):(themeLight?'rgba(87,107,137,.16)':'rgba(87,112,149,.18)');ctx.lineWidth=hot?1.35:.65;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke()}
  // nodes
  for(const n of state.graph.nodes){const x=cx+n.x*z,y=cy+n.y*z,r=n.size*Math.sqrt(z);if(x<-40||x>rect.width+40||y<-40||y>rect.height+40)continue;const selected=canonical(state.selected)===n.id,hover=state.graph.hover===n.id;if(selected||hover){ctx.beginPath();ctx.arc(x,y,r+7,0,Math.PI*2);ctx.fillStyle=selected?'rgba(116,130,255,.13)':'rgba(255,255,255,.06)';ctx.fill()}ctx.beginPath();ctx.arc(x,y,r+(selected?1.5:0),0,Math.PI*2);ctx.fillStyle=selected?'#9aa5ff':n.color;ctx.globalAlpha=selected?1:.88;ctx.fill();ctx.globalAlpha=1;if(selected){ctx.strokeStyle='#d8ddff';ctx.lineWidth=1;ctx.stroke()}const show=state.labels&&(selected||hover||z>1.12&&n.degree>=3||z>1.65);if(show){ctx.font=`${selected?'600':'500'} ${selected?11:9}px ui-monospace, SFMono-Regular, Menlo, monospace`;ctx.textAlign='center';ctx.textBaseline='top';const txt=truncate(n.label,z>1.5?30:20),w=ctx.measureText(txt).width;ctx.fillStyle=themeLight?'rgba(245,248,252,.93)':'rgba(8,13,23,.82)';ctx.fillRect(x-w/2-4,y+r+5,w+8,15);ctx.fillStyle=themeLight?'#334155':'#b9c5d7';ctx.fillText(txt,x,y+r+8)}}}
function wireObsidianInteractions(){const c=$('#obsidianCanvas');let panning=false,last=null;c.addEventListener('wheel',e=>{if(state.view!=='obsidian')return;e.preventDefault();const factor=e.deltaY<0?1.12:1/1.12;state.graph.zoom=clamp(state.graph.zoom*factor,.25,5);drawObsidian();updateZoomLabel()},{passive:false});c.addEventListener('pointerdown',e=>{if(state.view!=='obsidian')return;c.setPointerCapture(e.pointerId);const hit=graphHit(e);if(hit){state.graph.drag=hit;selectTable(hit)}else{panning=true;last={x:e.clientX,y:e.clientY}}});c.addEventListener('pointermove',e=>{if(state.view!=='obsidian')return;if(state.graph.drag){const rect=c.getBoundingClientRect(),n=state.graph.nodeMap.get(canonical(state.graph.drag));if(n){n.x=(e.clientX-rect.left-rect.width/2-state.graph.panX)/state.graph.zoom;n.y=(e.clientY-rect.top-rect.height/2-state.graph.panY)/state.graph.zoom;drawObsidian()}return}if(panning&&last){state.graph.panX+=e.clientX-last.x;state.graph.panY+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};drawObsidian();return}const h=graphHit(e);state.graph.hover=h?canonical(h):null;drawObsidian()});c.addEventListener('pointerup',()=>{panning=false;last=null;state.graph.drag=null});c.addEventListener('pointerleave',()=>{panning=false;state.graph.hover=null;drawObsidian()})}
function graphHit(e){const c=$('#obsidianCanvas'),r=c.getBoundingClientRect(),cx=r.width/2+state.graph.panX,cy=r.height/2+state.graph.panY,z=state.graph.zoom,x=e.clientX-r.left,y=e.clientY-r.top;let best=null,bd=Infinity;for(const n of state.graph.nodes){const d=Math.hypot(x-(cx+n.x*z),y-(cy+n.y*z));if(d<Math.max(12,n.size*z+6)&&d<bd){best=n;bd=d}}return best?.name||null}

function renderHybrid(){
  const svg=$('#hybridSvg');svg.innerHTML='';const defs=svgEl('defs');defs.innerHTML=`<filter id="softShadow" x="-50%" y="-50%" width="200%" height="200%"><feDropShadow dx="0" dy="10" stdDeviation="18" flood-opacity=".3"/></filter><linearGradient id="hyCenterGrad" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#26386a"/><stop offset="1" stop-color="#151f3e"/></linearGradient>`;svg.append(defs);const layer=svgEl('g',{transform:`scale(${state.hybrid.zoom})`});svg.append(layer);const center=selectedTable()||state.model.tables[0];if(!center)return;const cx=800,cy=500;const neigh=neighbors(center.name,state.depth).filter(n=>canonical(n)!==canonical(center.name)).slice(0,12);const inner=[];for(let i=0;i<neigh.length;i++){const a=-Math.PI/2+i*Math.PI*2/neigh.length;inner.push({name:neigh[i],x:cx+Math.cos(a)*330,y:cy+Math.sin(a)*245,a})}
  for(const n of inner){const path=svgEl('path',{d:`M${cx},${cy} Q${(cx+n.x)/2+Math.sin(n.a)*45},${(cy+n.y)/2-Math.cos(n.a)*45} ${n.x},${n.y}`,class:'hy-link'});layer.append(path)}
  // outer SQL objects targeting center or same migration
  let objs=state.model.objects.filter(o=>o.kind!=='table'&&(o.target&&canonical(o.target)===canonical(center.name))).slice(0,12);if(objs.length<8)objs=objs.concat(state.model.objects.filter(o=>o.kind!=='table'&&o.migration===center.migration&&!objs.includes(o)).slice(0,8-objs.length));const outer=[];objs.forEach((o,i)=>{const a=i*Math.PI*2/Math.max(1,objs.length)+.15;outer.push({...o,x:cx+Math.cos(a)*590,y:cy+Math.sin(a)*390,a})});for(const o of outer){const near=inner.length?inner.reduce((best,n)=>Math.hypot(o.x-n.x,o.y-n.y)<Math.hypot(o.x-best.x,o.y-best.y)?n:best,inner[0]):{x:cx,y:cy};layer.append(svgEl('path',{d:`M${near.x},${near.y} Q${(near.x+o.x)/2},${(near.y+o.y)/2} ${o.x},${o.y}`,class:'hy-link outer'}))}
  // outer nodes
  for(const o of outer){const g=svgEl('g',{class:'hy-object',transform:`translate(${o.x-72} ${o.y-18})`});g.append(svgEl('rect',{width:144,height:36,rx:18,fill:'#0f1929',stroke:kindColors[o.kind]||'#60708d'}),svgEl('text',{x:14,y:15,class:'hy-label'},truncate(shortName(o.name),20)),svgEl('text',{x:14,y:27,class:'hy-badge'},o.kind));layer.append(g)}
  for(const n of inner){const t=tableByName(n.name);const g=svgEl('g',{class:'hy-table',transform:`translate(${n.x-105} ${n.y-31})`});const r=svgEl('rect',{width:210,height:62,rx:11,fill:'#101b2d',stroke:canonical(n.name)===canonical(state.selected)?'#7d89ff':'#39506f'});g.append(r,svgEl('text',{x:14,y:25,class:'hy-label'},truncate(shortName(n.name),28)),svgEl('text',{x:14,y:43,class:'hy-badge'},`${t?.columns.length||0} campos · ${t?.degree||0} links`));g.style.cursor='pointer';g.addEventListener('click',()=>selectTable(n.name,{openInspector:true}));layer.append(g)}
  const cg=svgEl('g',{class:'hy-center',transform:`translate(${cx-160} ${cy-88})`});cg.append(svgEl('rect',{width:320,height:176,rx:19,fill:'url(#hyCenterGrad)',stroke:'#7b88ff','stroke-width':1.8}));cg.append(svgEl('text',{x:22,y:34,class:'hy-label','font-size':11},'TABELA EM FOCO'));cg.append(svgEl('text',{x:22,y:61,class:'hy-label','font-size':17,'font-family':'ui-monospace,monospace'},truncate(shortName(center.name),29)));cg.append(svgEl('text',{x:22,y:87,class:'hy-badge'},`${center.columns.length} campos · ${center.degree||0} relações · migration ${String(center.migration||0).padStart(4,'0')}`));center.columns.slice(0,4).forEach((c,i)=>cg.append(svgEl('text',{x:22,y:113+i*15,class:'hy-badge'},`${c.primary_key?'◆ ':''}${c.name}  ${truncate(c.data_type,20)}`)));layer.append(cg);$('#visibleCount').textContent=fmt(1+inner.length+outer.length);drawMiniMap()
}

function renderInspector(){const t=selectedTable(),body=$('#inspectorBody');if(!t){$('#inspectName').textContent='Selecione um objeto';$('#inspectMeta').innerHTML='';body.innerHTML='<div class="empty-state"><div class="empty-orbit">◇</div><p>Clique em uma tabela ou nó para examinar sua estrutura, relações e DDL.</p></div>';return}$('#inspectName').textContent=shortName(t.name);$('#inspectMeta').innerHTML=`<span class="meta-tag">TABLE</span>${t.migration?`<span class="meta-tag">M${String(t.migration).padStart(4,'0')}</span>`:''}${t.partitioning?'<span class="meta-tag">PARTITIONED</span>':''}`;
  if(state.inspectorTab==='structure'){const fkCols=new Set(t.foreign_keys.flatMap(f=>f.from_columns.map(canonical))),stats=t.statistics||{};body.innerHTML=`<dl class="detail-grid"><dt>Schema</dt><dd>${escapeHtml(t.name.includes('.')?t.name.split('.')[0]:'public')}</dd><dt>Campos</dt><dd>${t.columns.length}</dd><dt>Relações</dt><dd>${t.degree||0}</dd><dt>CHECKs</dt><dd>${(t.check_constraints||[]).length}</dd><dt>PK</dt><dd>${escapeHtml(t.primary_key.join(', ')||'—')}</dd>${t.partitioning?`<dt>Partitioning</dt><dd>${escapeHtml(t.partitioning.kind||'partition')} ${escapeHtml(t.partitioning.expression||'')}</dd>`:''}${stats.estimated_rows!=null?`<dt>Cardinalidade</dt><dd>~${fmt(stats.estimated_rows)} linhas</dd>`:''}${stats.total_bytes!=null?`<dt>Tamanho</dt><dd>${formatBytes(stats.total_bytes)}</dd>`:''}</dl><section class="inspector-section"><h3>COLUNAS</h3><div class="column-list">${t.columns.map(c=>`<div class="column-item advanced"><span class="col-key ${c.primary_key?'pk':fkCols.has(canonical(c.name))?'fk':''}">${c.primary_key?'PK':fkCols.has(canonical(c.name))?'FK':c.generated_expression?'ƒ':''}</span><b>${escapeHtml(c.name)}</b><span>${escapeHtml(c.data_type)}${c.nullable?' · NULL':''}${c.generated_expression?`<small>GENERATED ${escapeHtml(c.generated_kind||'')} · ${escapeHtml(c.generated_expression)}</small>`:''}</span></div>`).join('')}</div></section>${(t.check_constraints||[]).length?`<section class="inspector-section"><h3>CHECK CONSTRAINTS</h3>${t.check_constraints.map((c,i)=>`<div class="check-item"><b>${escapeHtml(c.name||`CHECK ${i+1}`)}</b><code>${escapeHtml(c.expression)}</code></div>`).join('')}</section>`:''}`}
  else if(state.inspectorTab==='relations'){const rels=state.model.relationships.filter(f=>canonical(f.from_table)===canonical(t.name)||canonical(f.to_table)===canonical(t.name));body.innerHTML=`<section class="inspector-section"><h3>${rels.length} RELAÇÕES</h3>${rels.map(f=>{const outgoing=canonical(f.from_table)===canonical(t.name),other=outgoing?f.to_table:f.from_table;return`<div class="relation-item" data-table="${escapeHtml(other)}"><b>${outgoing?'→':'←'} ${escapeHtml(shortName(other))}</b><span>${escapeHtml((outgoing?f.from_columns:f.to_columns).join(', '))} ${outgoing?'→':'←'} ${escapeHtml((outgoing?f.to_columns:f.from_columns).join(', '))}${f.on_delete?` · ON DELETE ${escapeHtml(f.on_delete)}`:''}</span></div>`}).join('')||'<div class="empty-state"><p>Sem relações FK.</p></div>'}</section>`;$$('.relation-item',body).forEach(x=>x.addEventListener('click',()=>selectTable(x.dataset.table)))}
  else body.innerHTML=`<pre class="ddl-code">${escapeHtml(t.ddl||'DDL indisponível')}</pre>`;
}

function formatBytes(v){v=Number(v)||0;if(v<1024)return `${v} B`;const u=['KB','MB','GB','TB'];let i=-1;do{v/=1024;i++}while(v>=1024&&i<u.length-1);return `${v.toLocaleString('pt-BR',{maximumFractionDigits:1})} ${u[i]}`}
function updateDiffButton(){const b=$('#schemaDiffBtn');if(!b)return;const n=state.schemaDiff?.summary?.total_changes||0;b.disabled=!(state.fileModel&&state.liveModel);b.dataset.count=n;b.querySelector('span').textContent=n?`Diff ${fmt(n)}`:'Schema Diff'}
function openSchemaDiff(){if(!(state.fileModel&&state.liveModel)){toast('Abra um SQL e conecte um banco para comparar');return}state.schemaDiff=diffSchemas(state.fileModel,state.liveModel);const d=state.schemaDiff,s=d.summary;$('#diffSummary').innerHTML=`<div><b>${fmt(s.total_changes)}</b><span>mudanças</span></div><div><b>${fmt(s.added_tables)}</b><span>tabelas só no vivo</span></div><div><b>${fmt(s.removed_tables)}</b><span>tabelas só no arquivo</span></div><div><b>${fmt(s.changed_tables)}</b><span>tabelas alteradas</span></div>`;const groups=[['Tabelas adicionadas',d.tables.added],['Tabelas ausentes no vivo',d.tables.removed],['Tabelas alteradas',(d.tables.changed||[]).map(x=>x.name||x.table||String(x))],['Objetos adicionados',(d.objects.added||[]).map(x=>`${x.kind}: ${x.name}`)],['Objetos ausentes',(d.objects.removed||[]).map(x=>`${x.kind}: ${x.name}`)]];$('#diffDetails').innerHTML=groups.filter(([,a])=>a?.length).map(([title,a])=>`<section><h3>${title} <em>${a.length}</em></h3>${a.slice(0,60).map(x=>`<div>${escapeHtml(typeof x==='string'?x:(x.name||JSON.stringify(x)))}</div>`).join('')}</section>`).join('')||'<div class="diff-clean">Schemas equivalentes no escopo comparado.</div>';$('#diffDialog').showModal()}
function showSearch(q){state.query=q;const box=$('#searchResults');if(!q.trim()){box.hidden=true;return}const terms=q.trim().toLowerCase().split(/\s+/);const items=[];for(const t of state.model.tables){const hay=`table ${t.name} ${t.columns.map(c=>c.name).join(' ')}`.toLowerCase();if(terms.every(x=>hay.includes(x)))items.push({kind:'table',name:t.name,sub:`${t.columns.length} campos · ${t.degree||0} relações`,migration:t.migration,table:t.name})}for(const o of state.model.objects){if(o.kind==='table')continue;const hay=`${o.kind} ${o.name} ${o.target||''}`.toLowerCase();if(terms.every(x=>hay.includes(x)))items.push({kind:o.kind,name:o.name,sub:o.target?`em ${o.target}`:kindLabels[o.kind],migration:o.migration,table:o.target})}items.sort((a,b)=>(a.kind==='table'?-1:1)-(b.kind==='table'?-1:1));box.innerHTML=items.slice(0,36).map((x,i)=>`<button class="search-item ${i===0?'active':''}" type="button" data-i="${i}"><i style="color:${kindColors[x.kind]}">${kindShort[x.kind]}</i><span><b>${escapeHtml(shortName(x.name))}</b><small>${escapeHtml(x.sub||'')}</small></span><em>M${String(x.migration||0).padStart(4,'0')}</em></button>`).join('')||'<div class="empty-state"><p>Nenhum objeto encontrado.</p></div>';box.hidden=false;$$('.search-item',box).forEach((b,i)=>b.addEventListener('click',()=>{const x=items[i];if(x.table&&tableByName(x.table))selectTable(x.table,{openInspector:true});else{state.migration=x.migration;renderMigrations();renderCurrent();toast(`${x.kind}: ${x.name}`)}hideSearch()}))}
function hideSearch(){$('#searchResults').hidden=true}

function zoomCurrent(f){if(state.view==='obsidian'){if(!state.enhancer?.zoomObsidian(f)){state.graph.zoom=clamp(state.graph.zoom*f,.25,5);drawObsidian()}}else if(state.view==='relational'){state.rel.userPositioned=true;state.rel.zoom=clamp(state.rel.zoom*f,.2,2.5);applyRelTransform()}else if(state.view==='mindset'){state.mind.zoom=clamp(state.mind.zoom*f,.5,1.7);renderMindset()}else{state.hybrid.zoom=clamp(state.hybrid.zoom*f,.5,1.6);renderHybrid()}updateZoomLabel()}
function updateZoomLabel(){let z=state.view==='obsidian'?state.graph.zoom:state.view==='relational'?state.rel.zoom:state.view==='mindset'?state.mind.zoom:state.hybrid.zoom;if(state.view==='obsidian'&&state.enhancer?.rt.sigmaRenderer){try{z=1/state.enhancer.rt.sigmaRenderer.getCamera().getState().ratio}catch(_){}}$('#zoomOutput').textContent=`${Math.round(z*100)}%`}
function fitCurrent(){if(state.view==='obsidian'){if(!state.enhancer?.fitObsidian()){state.graph.zoom=1;state.graph.panX=state.graph.panY=0;drawObsidian()}}else if(state.view==='relational'){state.rel.userPositioned=false;if(!state.enhancer?.fitRelational()) {state.rel.zoom=1;state.rel.panX=state.rel.panY=0;applyRelTransform()}}else if(state.view==='mindset'){state.mind.zoom=1;renderMindset()}else{state.hybrid.zoom=1;renderHybrid()}updateZoomLabel()}
function focusCurrent(){if(!state.selected)return;if(state.view==='relational')renderRelational();else if(state.view==='obsidian'){if(!state.enhancer?.focusObsidian()){const n=state.graph.nodeMap?.get(canonical(state.selected));if(n){state.graph.panX=-n.x*state.graph.zoom;state.graph.panY=-n.y*state.graph.zoom;drawObsidian()}}}else renderCurrent()}
function wireRelationalInteractions(){const v=$('#relationalView');let drag=false,last=null;v.addEventListener('wheel',e=>{if(state.view!=='relational')return;e.preventDefault();state.rel.zoom=clamp(state.rel.zoom*(e.deltaY<0?1.1:1/1.1),.35,2.5);applyRelTransform()},{passive:false});v.addEventListener('pointerdown',e=>{if(state.view!=='relational'||e.target.closest('.table-card'))return;drag=true;last={x:e.clientX,y:e.clientY};v.setPointerCapture(e.pointerId)});v.addEventListener('pointermove',e=>{if(drag&&last){state.rel.userPositioned=true;state.rel.panX+=e.clientX-last.x;state.rel.panY+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};applyRelTransform()}});v.addEventListener('pointerup',()=>{drag=false;last=null})}

function drawMiniMap(){const c=$('#miniCanvas'),r=c.getBoundingClientRect();if(!r.width||!r.height)return;const d=Math.min(2,devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle=document.body.classList.contains('light')?'#dce4ee':'#20304a';if(state.view==='obsidian'&&state.graph.nodes.length){const xs=state.graph.nodes.map(n=>n.x),ys=state.graph.nodes.map(n=>n.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);for(const n of state.graph.nodes){const x=7+(n.x-minX)/(maxX-minX||1)*(r.width-14),y=7+(n.y-minY)/(maxY-minY||1)*(r.height-14);ctx.beginPath();ctx.arc(x,y,1.2,0,Math.PI*2);ctx.fill()}}else{for(let i=0;i<35;i++){const h=hash32(`${state.view}-${i}`);ctx.fillRect(8+(h%110),7+((h>>>8)%66),2,2)}}}

function exportCurrent(){if(state.view==='obsidian'){if(state.enhancer?.exportObsidian())return;const c=$('#obsidianCanvas');downloadUrl(c.toDataURL('image/png'),`PhxMindSetSQL_${state.view}.png`);toast('PNG exportado em resolução Retina')}else if(['mindset','hybrid'].includes(state.view)){const svg=$(`#${state.view}Svg`);const data=`<?xml version="1.0" encoding="UTF-8"?>
${new XMLSerializer().serializeToString(svg)}`;downloadBlob(new Blob([data],{type:'image/svg+xml'}),`PhxMindSetSQL_${state.view}.svg`);toast('SVG vetorial exportado')}else exportRelational()}
function exportRelational(){const l=state.rel.layout;if(!l)return;const pad=30;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of l.pos.values()){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x+(p.w||238));maxY=Math.max(maxY,p.y+(p.h||180))}const W=maxX-minX+pad*2,H=maxY-minY+pad*2;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="${minX-pad} ${minY-pad} ${W} ${H}"><rect x="${minX-pad}" y="${minY-pad}" width="${W}" height="${H}" fill="#080d17"/>`;const nameSet=new Set(l.names);for(const fk of state.model.relationships){const a=canonical(fk.from_table),b=canonical(fk.to_table);if(!nameSet.has(a)||!nameSet.has(b))continue;const pa=l.pos.get(a),pb=l.pos.get(b);if(!pa||!pb)continue;const x1=pa.x+119,y1=pa.y+50,x2=pb.x+119,y2=pb.y+50;s+=`<path d="M${x1} ${y1} C${(x1+x2)/2} ${y1} ${(x1+x2)/2} ${y2} ${x2} ${y2}" fill="none" stroke="#536b91" stroke-width="1.5"/>`}for(const n of l.names){const t=tableByName(n),p=l.pos.get(n);if(!t||!p)continue;s+=`<rect x="${p.x}" y="${p.y}" width="238" height="${Math.max(70,p.h||120)}" rx="10" fill="#111c2e" stroke="${canonical(t.name)===canonical(state.selected)?'#7d89ff':'#344b6d'}"/><text x="${p.x+12}" y="${p.y+24}" fill="#eff4ff" font-size="11" font-family="monospace">${escapeHtml(shortName(t.name))}</text>`;t.columns.slice(0,7).forEach((c,i)=>{s+=`<text x="${p.x+12}" y="${p.y+48+i*21}" fill="#aebbd0" font-size="8" font-family="monospace">${escapeHtml(c.name)}  ${escapeHtml(truncate(c.data_type,16))}</text>`})}s+='</svg>';downloadBlob(new Blob([s],{type:'image/svg+xml'}),'PhxMindSetSQL_relacional.svg');toast('DER exportado como SVG')}
function downloadUrl(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob);downloadUrl(u,name);setTimeout(()=>URL.revokeObjectURL(u),5000)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
function setStatus(msg){$('#statusText').textContent=msg}


function setEngine(label){const el=$('#renderEngine');if(el)el.textContent=label||'SVG/Canvas'}

init();
